### ISSUE TITLE
No rules found within configuration?

### ISSUE THREAD

**Issue by jaminroe** [shinnn/vscode-stylelint#1]
I’m trying to setup style lint extension with VS Code. I added the one line like you say to the config file, but I keep getting this message popping up:
<img width="309" alt="screen shot 2015-12-19 at 4 58 17 pm" src="https://cloud.githubusercontent.com/assets/1559447/11915602/b8775620-a67b-11e5-8101-ce351102faa2.png">

{
  "stylelint.enable": true
}

Thank you!

**Comment by shinnn** [comment]
Is it really "Failed to execute git", instead of "No rules found within configuration"?

**Comment by jaminroe** [comment]
Sorry updated my post. Doing too many things and frustrated like hell with gulp right now haha

**Comment by shinnn** [comment]
Although this is the default behavior of [stylelint](http://stylelint.io/), it's too strict to use it as an editor plugin. OK, I'll update vscode-stylelint to hide "No rules found" error.

**Comment by jaminroe** [comment]
What does that mean "no rules". No errors? I was writing jibberish in a CSS file and it didn't pickup on the errors so I'm confused... Is this supposed to work out of the box?

**Comment by shinnn** [comment]
> What does that mean "no rules"

Just what the error said. No [rules](http://stylelint.io/?/docs/user-guide/rules.md).

**Comment by jaminroe** [comment]
Oh LOL! My CSS file was about 500 lines though. So must be something wrong. ¯\_(ツ)_/¯

**Comment by jaminroe** [comment]
Could you answer my last question though please? Thank you! I had CSS m, about 500 lines worth. So why would it not work? I purposely wrote invalid CSS too to test.

**Comment by shinnn** [comment]
> Could you answer my last question though please?

![image](https://cloud.githubusercontent.com/assets/1131567/11962681/fa3945ea-a924-11e5-884a-6d39e4abbf7a.png)

https://help.github.com/articles/closing-issues-via-commit-messages/

> why would it not work?

https://github.com/shinnn/vscode-stylelint/issues/1#issuecomment-166034303

**Comment by jaminroe** [comment]
Ohhhh, it's not an editor plug-in. I see :( Is there an extension you can recommend for live editing?
