### ISSUE TITLE
Enable this extension by default

### ISSUE THREAD

**Issue by jp7677** [shinnn/vscode-stylelint#10]
Just like the Microsoft extensions we should enable the extension by default. See [https://github.com/Microsoft/vscode-tslint/blob/69cf5a356eabd22e25100ecc7e8ae024bea4778e/tslint/package.json#L40](https://github.com/Microsoft/vscode-tslint/blob/69cf5a356eabd22e25100ecc7e8ae024bea4778e/tslint/package.json#L40) and [https://github.com/shinnn/vscode-stylelint/pull/9/commits/72df16414b7ff50b8b249484c64da3adddc026b3](https://github.com/shinnn/vscode-stylelint/pull/9/commits/72df16414b7ff50b8b249484c64da3adddc026b3).

**Comment by shinnn** [comment]
No need to open a new issue. I've already aware of that. https://github.com/shinnn/vscode-stylelint/issues/8#issuecomment-216097160
