### ISSUE TITLE
By default, all node_modules and bower_components are ignored?

### ISSUE THREAD

**Issue by syakuis** [shinnn/vscode-stylelint#100]
By default, all node_modules and bower_components are ignored?

![2017-08-21 10 48 27](https://user-images.githubusercontent.com/6147878/29500883-468fc8f6-865f-11e7-8dbf-410925c6e87c.png)

.stylelintrc

```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "at-rule-empty-line-before": null
  }
}
```

.stylelintignore

```
node_modules/
bower_components/
dist/
```

Why is this? :(  sorry, I speak a little English.

**Comment by shinnn** [comment]
This is stylelint's default behavior and you should not ask about it here. Check the [stylelint README](https://github.com/stylelint/stylelint/tree/8.0.0#need-help) and you'll see where  this issue should have been posted.
