### ISSUE TITLE
vscode-stylelint ignores the stylelintignore?

### ISSUE THREAD

**Issue by proProbe** [shinnn/vscode-stylelint#101]
Hello,

I just started to look at stylelint yesterday and found it to be amazing. I would love to add it to my vscode workflow but it seems to be a bug where .stylelintignore is not being used? Whenever I start vscode, it tries to lint through all my files that I have including the ignored files. I am only trying to use it on .less-files and ignore .css-files. But it doesnt seem to matter. This results in a huge loadtime during startup of vscode.

![capture](https://user-images.githubusercontent.com/3802899/29657218-3af42a82-88b7-11e7-94b3-7f7a60461314.PNG)

Do you perhaps any solution that we can apply to this?

**Comment by shinnn** [comment]
I confirmed that this is a bug of the stylelint; its CLI reads `.stylelintignore` but the API doesn't.

Open a new issue on https://github.com/stylelint/stylelint/issues with the *detailed* information.

**Comment by king-king** [comment]
omg
