### ISSUE TITLE
Specify .stylelintrc to use

### ISSUE THREAD

**Issue by gkweb** [shinnn/vscode-stylelint#102]
If I have a project directory structure similar to below where the .stylelintrc is nested within the project: 

`project`
... `lib`
... `root`
........ `ui-stuff-in-here`
............ `package.json`
............ `.stylelintrc`

If opening: `code ui-stuff-in-here` then .stylelintrc will be loaded.
If opening the project root: `code project` then .stylelintrc will **NOT** be loaded.

Is it possible to specify the relative location?

**Comment by shinnn** [comment]
> If opening the project root: code project then .stylelintrc will __NOT__ be loaded.

Read https://github.com/shinnn/vscode-stylelint/issues/80.

> Is it possible to specify the relative location?

This bug is fixed in https://github.com/stylelint/stylelint/commit/c2e3de9524d0961b370020d6f48c327258d71ff3 and you'll never need the possibility to set the location if stylelint 8.1.0 is released.
