### ISSUE TITLE
vscode-stylelint show error for deprecated stylelint rules 

### ISSUE THREAD

**Issue by volosovich** [shinnn/vscode-stylelint#104]
Hi
I found issue - https://github.com/shinnn/vscode-stylelint/issues/16

In my project we use "stylelint": "^5.1.0"
So, I'm receiving a lot of messages like `Error stylelint: Undefined rule number-zero-length-no-unit`
Does it exist way, to check version from package.json and show error or no in some case like in my case.
PS Of course I'll check if we can switch to newest version
Thanks

**Comment by shinnn** [comment]
> Does it exist way, ...

No, and I'm unwilling to add it to this extension.

> Of course I'll check if we can switch to newest version

Upgrade to stylelint v8 is not so hard. All removed rules are listed in https://github.com/stylelint/stylelint/blob/8.0.0/CHANGELOG.md#800.
