### ISSUE TITLE
additionalDocumentSelectors not working properly

### ISSUE THREAD

**Issue by bmfteixeira** [shinnn/vscode-stylelint#105]
Added `"stylelint.additionalDocumentSelectors": ["vue"]` on Workspace setting, reloaded the window, and still not working. Any extra settings needed?

**Comment by shinnn** [comment]
1. Search https://stylelint.io/user-guide/processors/ or https://npms.io/ for a stylelint proceccor that supports .vue syntax.
2. Install it to your project.
3. Add [`processors`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#processors) property to your stylelint configuration.
