### ISSUE TITLE
How to use a processor as a right way?

### ISSUE THREAD

**Issue by vega-wong** [shinnn/vscode-stylelint#111]
I want lint the css code in the css file and html file.

but,,,,     i know that i must use a processor such as [stylelint-processor-html](https://github.com/ccbikai/stylelint-processor-html), at the same time, my css file does not work!

i must remove all the processors i use. Any processor exists in the `.stylelintrc.js` will make all the `css/scss/less` file not work!  

what happen? and how i can resolve it?

**Comment by shinnn** [comment]
This is not an issue of this extension but just a usage question of stylelint. Ask the stylelint team members about it instead.

**Comment by vega-wong** [comment]
![5cb22284d8444f82db7ebd19381a0c9e](https://user-images.githubusercontent.com/17271745/31936952-a8b86e8a-b8e5-11e7-879b-1d1530980bae.jpg)
like that!!

**Comment by shinnn** [comment]
Nah. it just works for both CSS and HTML.

![image](https://user-images.githubusercontent.com/1131567/31937765-6d09e7be-b8f0-11e7-892e-810c02b6f82b.png)

**Comment by vega-wong** [comment]
@shinnn  oh my god!  can you let me see your `stylelint.config.js`?  which processor did you used?

**Comment by shinnn** [comment]
```javascript
module.exports = {
  processors: ['stylelint-processor-html'],
  rules: {
    'length-zero-no-unit': true
  }
};
```

**Comment by vega-wong** [comment]
oh thanks! my me i known what happen about that!....
emmmm....   i can't find any processor that can use with any stylesheet file as the same time as html/vue or other file. may be i need make one by myself!   ths a lot!! :)

**Comment by shinnn** [comment]
> may be i need make one by myself

It's no longer needed if https://github.com/stylelint/stylelint/pull/2975 is landed.
