### ISSUE TITLE
Feature request: Add support for styled components

### ISSUE THREAD

**Issue by alexandernanberg** [shinnn/vscode-stylelint#112]
My current config with [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) works in the terminal but not inside VS Code. It's possible that I've overlooked something, but otherwise this would be a very nice feature.

**Comment by shinnn** [comment]
Use [`additionalDocumentSelectors`](https://github.com/shinnn/vscode-stylelint/tree/254cfadf345cde48f5ae55ebf078a15a51eb86da#stylelintadditionaldocumentselectors) option.

**Comment by shinnn** [comment]
From [v0.35.0](https://github.com/shinnn/vscode-stylelint/commit/483a4238841e08d1fb030a61739ee1b3122cac36) onward, this extension automatically applies stylelint to CSS-in-JS when either stylelint-processor-glamorous or stylelint-processor-styled-components is installed and enabled.
