### ISSUE TITLE
vscode error "stylelint: Undefined rule declaration-block-no-ignored-properties"

### ISSUE THREAD

**Issue by dannypule** [shinnn/vscode-stylelint#113]
stylelint - npm package version: 7.7.1
stylelint - vscode exstenstion version: 0.30.0

I'm receiving the following error in vscode: "stylelint: Undefined rule declaration-block-no-ignored-properties"

It's not possible for me to upgrade my version of stylelint or change the stylelint config file as I'm not the main project owner. Is there a way to overcome this issue through updating my user settings in vscode?

**Comment by shinnn** [comment]
1. Uninstall the existing VSCode extension v0.30.0.
2. Download and extract https://github.com/shinnn/vscode-stylelint/archive/27ac10d6d727730a262e39d2b2903f6310309727.zip.
3. `cd` to the extracted directory and run `npm install`.
4. Move the directory to your VSCode extension folder, for example `~/vscode/extensions` on macOS.
5. Restart VSCode.
