### ISSUE TITLE
Feature request: Add configFile configuration option

### ISSUE THREAD

**Issue by jamesvclements** [shinnn/vscode-stylelint#114]
Thanks for making this!

Support [the config file option](https://stylelint.io/user-guide/node-api/#configfile) so that we can provide a relative or absolute path to the StyleLint config file and have linting regardless of workspace directory.

I think it'd go [right around here.](https://github.com/shinnn/vscode-stylelint/blob/cfe58b0e2f257493a163d9973832eff1de0b2d75/index.js#L13)

**Comment by shinnn** [comment]
I have no interest in this feature because you can easily achieve it in other ways.

**Comment by jamesvclements** [comment]
@shinnn Cool, do you mind explaining one of the other ways?

**Comment by shinnn** [comment]
Add [`extends`](https://stylelint.io/user-guide/configuration/#extends) option to your [`stylelint.config`](https://github.com/shinnn/vscode-stylelint/tree/254cfadf345cde48f5ae55ebf078a15a51eb86da#stylelintconfig).
