### ISSUE TITLE
`--fix` capability no longer blocked by `styelint`

### ISSUE THREAD

**Issue by njgraf512** [shinnn/vscode-stylelint#115]
@shinnn, you write in #99 that adding autofix capability to the plugin is blocked on stylelint/stylelint#2710, but I just wanted to point out that a PR has been landed that resolved that task. I noticed that you removed the "help wanted" tag on #99, so I just wanted to send this note over to you in hopes that someone might have the time to work on a PR. BTW, it would be really great if the implemented feature included options for running the feature from both the command palette and automatically on save. Thanks for all your work on this great project!

(I would have commented on #99 directly, but comments there are locked.)

**Comment by shinnn** [comment]
I updated my last comment. https://github.com/shinnn/vscode-stylelint/issues/99#issuecomment-333583991

**Comment by jas99** [comment]
@shinnn they just released  stylelint/stylelint#2710 in 8.3.0
