### ISSUE TITLE
Update stylelint from v8.2.0 to v8.3.0

### ISSUE THREAD

**Issue by aweiu** [shinnn/vscode-stylelint#116]
now,the newest stylelint-config-standard is 18.0.0.
if i use it,the vscode-stylelint will toast some undefined-rule errors

**Comment by dmy147** [comment]
Update stylelint from v8.2.0 to v8.3.1

**Comment by aweiu** [comment]
I have updated to v8.3.1,but the problem is still there

**Comment by aweiu** [comment]
When to submit the vscode market update？

**Comment by shinnn** [comment]
When I want to.

**Comment by shinnn** [comment]
f48ec35e7b831de30b90375e45a25f29f39868e2
