### ISSUE TITLE
My stylelint config with stylelint-scss is not working

### ISSUE THREAD

**Issue by diego-codes** [shinnn/vscode-stylelint#122]
I don't know if this is the right project to request this addition, but [`stylelint-scss`](https://github.com/kristerkari/stylelint-scss) has two new rules `at-mixin-named-arguments` and `at-function-named-arguments` that are making this plugin throw errors in VSCode.

**Comment by shinnn** [comment]
It already works.

```console
$ npm ls stylelint stylelint-scss
/Users/shinnn/src/test
├── stylelint@8.3.1 
└── stylelint-scss@2.2.0 
```

`stylelint.config.js`:

```js
module.exports = {
  plugins: [
      'stylelint-scss'
    ],
    rules: {
      'scss/at-mixin-named-arguments': 'always',
      'scss/at-function-named-arguments': 'always'
    }
};
```

<img width="1102" alt="img" src="https://user-images.githubusercontent.com/1131567/33590093-6de87d44-d9c0-11e7-89a2-4119b37c6268.png">
