### ISSUE TITLE
Missing support for stylelint's cosmiconfig

### ISSUE THREAD

**Issue by elektronik2k5** [shinnn/vscode-stylelint#125]
Hello and thank you for creating this extension! :)

After configuring stylelint with `.stylelintrc.yaml` and making sure it works fine via the CLI, I added your extension to vscode - expecting it to work. An hour later, after reading the readme and various closed issues I looked in the source code and discovered only `.stylelintrc` (in JSON) and `stylelint.config.js` are supported - hard coded.
https://github.com/shinnn/vscode-stylelint/blob/f48ec35e7b831de30b90375e45a25f29f39868e2/index.js#L29
Once I converted the tidy `.stylelintrc.yaml` to an ugly `.stylelintrc` JSON, the extension began working.

**Can you please add support for cosmiconfig, so anything stylelint accepts will work for the extension too?**
[Relevant documentation in stylelint.](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#loading-the-configuration-object)

If not (or until then), **please add a clear note about this limitation** to save users' time.
I can look into making PRs for these. I'm clueless about vscode extensions, but can find the time to learn :).

Another friendly suggestion: I saw lots of users are opening issues because they didn't read the documentation - either of the extension or stylelint's. I believe that if you add notifications about common (mis)configuration issues, it will save time to you and the users.
Example: in my case, a message saying "No stylelint configuration found" once the extension is installed would have pointed me directly at the root cause.
I've seen some extensions implementing this technique and can attest to its effectiveness.

Thanks again for your work!

**Comment by elektronik2k5** [comment]
Hello? @shinnn

**Comment by shinnn** [comment]
Hello.

**Comment by elektronik2k5** [comment]
I wrote a bunch of text at the [top of this page](https://github.com/shinnn/vscode-stylelint/issues/125#issue-282434350) :)
