### ISSUE TITLE
Drupal doesn't include stylelint-config-standard

### ISSUE THREAD

**Issue by Nick-Hope** [shinnn/vscode-stylelint#126]
I have installed stylelint 0.31.0 in vscode 1.19.0
In a Drupal installation under Xampp, if I open for example _C:\xampp\htdocs\drupal\core\themes\bartik\css\layout.css_, I get an error message `stylelint: Could not find "stylelint-config-standard". Do you need a 'configBasedir'` However if I open _C:\xampp\htdocs\drupal\themes\mytheme\css\style.css_ then I do not, and linting appears to work.

In the vscode user settings I have this set:
```
{
   "stylelint.enable": true,
    "css.validate": false,
    "scss.validate": false
}
```
In the stylelint configuration options I have left these defaults:
```

  "stylelint.additionalDocumentSelectors": [],
  "stylelint.config": null,
  "stylelint.configOverrides": null,
  "stylelint.enable": true,
```
Why would this error occur only for files in some locations?

**Comment by Nick-Hope** [comment]
I found a .stylelintrc.json file in C:\xampp\htdocs\drupal\core. By deleting it, vscode-stylelint now works again without the error message. I don't know why that file is there, but it seems to have been packaged with Drupal 8 core, maybe intentionally or maybe accidentally. There are also a couple of other similar files there such as .eslintrc.json.

**Comment by shinnn** [comment]
Open an issue for Drupal instead.

**Comment by Nick-Hope** [comment]
Thank you. Done: https://www.drupal.org/project/drupal/issues/2931940

**Comment by shinnn** [comment]
@Nick-Hope Thanks.

**Comment by shinnn** [comment]
https://www.drupal.org/project/drupal/issues/2931940#comment-12407059

> Thank you. Just running `npm install` in the `core` folder made the error message disappear in vscode.
