### ISSUE TITLE
IntelliSense for .stylelintrc.js?

### ISSUE THREAD

**Issue by mcdado** [shinnn/vscode-stylelint#134]
I love the fact that the JSON configuration file gets IntelliSense autocompletion.
I image it must be harder, but would it be possible to add the same support to `.stylelintrc.js`?

My configuration looks something like this:
```js
module.exports = {
  "extends": [
    'stylelint-config-recommended-scss',
    'stylelint-config-standard',
    // 'stylelint-config-sass-guidelines'
  ],
  "plugins": ["stylelint-scss"],
  "rules": {
    "color-hex-length": null,
    "declaration-colon-newline-after": null,
    "declaration-property-value-blacklist": { "transition": ["all"] },
    "no-descending-specificity": null, // TODO: revisit later, for now it's too noisy.
  }
};
```

I would convert it to JSON, but I'd lose the possibility to comment it. The above is just an example, I have many more comments. But as far as I know only JSON supports IntelliSense.

See also:
https://github.com/davidtheclark/cosmiconfig/issues/20

**Comment by shinnn** [comment]
Sorry but I won't implement this feature by myself because I don't have much interest in it.

Even if you submit a good pull request, I won't merge it because I don't have enough energy to update IntelliSense on every new release of stylelint.
