### ISSUE TITLE
Auto disable native CSS/SCSS linters when config is present

### ISSUE THREAD

**Issue by romulof** [shinnn/vscode-stylelint#135]
Is it possible to suppress VSCode native linters for CSS and SCSS when this extension detects a Stylelint configuration file? Or at least make this onde opt-in configuration.

This way we could leave `stylelint.enable` always _true_ and forget about these other configs:
```json
{
  "css.validate": false,
  "scss.validate": false
}
```

Currently I have to set VSCode Workspace config for each project, and this would make a solution that works out-of-the box everywhere.

**Comment by shinnn** [comment]
There is `getConfiguration` API but `setConfiguration` doesn't seem to exist. https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace
