### ISSUE TITLE
How to allow double slash comments in PostCSS 

### ISSUE THREAD

**Issue by marvin1023** [shinnn/vscode-stylelint#136]
Using this vscode plugin, as follows:

![image](https://user-images.githubusercontent.com/1264591/35315419-4181259e-0107-11e8-962b-d554583f2b82.png)

but Using CLI，`stylelint input.css --syntax scss` is ok。

I can't find the setting syntax in this vscode plugin:

![image](https://user-images.githubusercontent.com/1264591/35315624-4d43ad4c-0108-11e8-8508-dda98062a7fa.png)

**Comment by shinnn** [comment]
Not a vscode-stylelint issue. Support questions should be directed elsewhere.
