### ISSUE TITLE
VSCode Stylelint ignores .stylelintignore

### ISSUE THREAD

**Issue by AlesMenzel** [shinnn/vscode-stylelint#139]
The extention does not take into account `.stylelintignore` as is from the [stylelint documentation](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#stylelintignore).

Instead `ignoreFiles` must be used in `.stylelintrc` file like:
```
{
  ...
  "ignoreFiles": ["node_modules", "**/*.css"] // Check only SASS files
}
```

**Comment by shinnn** [comment]
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/132
