### ISSUE TITLE
does not activate for less files

### ISSUE THREAD

**Issue by patsissons** [shinnn/vscode-stylelint#14]
I believe this is just a `package.json` configuration issue. I'll submit a PR for this shortly.

**Comment by onedesert** [comment]
If you open a "scss" file before then check on less. I hope this helps.

**Comment by patsissons** [comment]
similarly you can also open any css file to activate the plugin. Once #15 is merged in this should be resolved (which i see is now conflicted, I'll try and take care of the conflict tomorrow).

**Comment by onedesert** [comment]
Thanks, btw this feature is awsome! I've change my local copy of vscode-stylelint to match new less listener on package.json. If you need any help on this on a future just @ me. Thanks.

**Comment by shinnn** [comment]
@patsissons @onedesert Can you try 0.8.4?

**Comment by onedesert** [comment]
@shinnn not working for me.

**Comment by shinnn** [comment]
No useful feedback.

**Comment by onedesert** [comment]
@shinnn sorry, for me previos version was working after add locally the less listener in to the package json. Also was working for less files after open and lint a .scss file on same project (vscode window). But with this last version is not working less neither scss. When I'll have a moment I'll try to give you more usefull feedback
