### ISSUE TITLE
Suggestion: Enable light bulb prompt to add disable/enable rule

### ISSUE THREAD

**Issue by leocaseiro** [shinnn/vscode-stylelint#140]
Very similar what happens in the `vscode-tslint`.

Docs to implement are: 
* https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namecodeactionprovideraspan-classcodeitem-id565codeactionproviderspan
* https://code.visualstudio.com/docs/extensions/example-debuggers

PS: I'm happy to give a try if you are keen to merge it.

**Comment by shinnn** [comment]
Thanks for the suggestion but I don't have much interest in this feature.
