### ISSUE TITLE
Stylelint 8.4.0 -> 9.0.0

### ISSUE THREAD

**Issue by fuhlig** [shinnn/vscode-stylelint#143]
[Stylelint 9.0.0 Release](https://github.com/stylelint/stylelint/releases/tag/9.0.0)

**Comment by abdonrd** [comment]
Does the plugin not use the version that is installed in the project?

**Comment by fuhlig** [comment]
I guess not as the plugin did not pickup a rule that was introduced in 8.4.0 before it was updated. Will verify that tomorrow

**Comment by fuhlig** [comment]
Setting `"selector-pseudo-element-blacklist": ["before", "/^my-/i"]` (introduced in v9) vscode-stylelint throws an error `stylelint: undefined rule selector-pseudo-element-blacklist` while the CLI lints correctly. Therefor i guess the stylelint dependency has to be updated in order to work with vscode

**Comment by shinnn** [comment]
> Does the plugin not use the version that is installed in the project?

https://github.com/shinnn/vscode-stylelint/issues/67
