### ISSUE TITLE
Undefined rule font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by livemirsi** [shinnn/vscode-stylelint#145]
stylelint: 0.33.0
vscode: 1.20.1
stylelint-config-standard: 18.0
Hello. You can update stylelint in extension?

**Comment by shinnn** [comment]
This extension already uses [the current latest version](https://github.com/shinnn/vscode-stylelint/blob/a9471706b179e6d3a3f39a002206755f921bfd2f/npm-shrinkwrap.json#L1686).
