### ISSUE TITLE
vscode stylelint configBasedir

### ISSUE THREAD

**Issue by petrdanecek** [shinnn/vscode-stylelint#146]
I recently migrated from Atom to VScode and trying to set the linting. I'm having my project split to more subdirectories with different versions of node_modules..the file structure is like:

```
workdir:/
 .stylelintrc
 .eslintrc
 frontend/
   pageA/
     node_modules
   pageB/
     some_different_node_modules
```

I'm having problem with relative paths in .stylelintrc. The "extend" full path works well, but I would prefer to keep the paths relative there.

I'm getting this VScode error:
> stylelint: Could not find "stylelint-config-recommended-scss". Do you need a `configBasedir`?
![image](https://user-images.githubusercontent.com/29194829/36888300-248cd342-1df5-11e8-93cd-8b2db1bd32e6.png)

I fixed the issue by using relative path in stylelintrc

> {
>   "extends": "./frontend/pageA/node_modules/stylelint-config-recommended-scss",
>  }

but the path is hardcoded which I don't like.

The stylelint provides configBaseDir (https://stylelint.io/user-guide/postcss-plugin/#configbasedir) option.
Is there any plan to have configBasedir option available in your plugin?

**Comment by shinnn** [comment]
Enclose lines where number of indent is important by code blocks.

```
workdir:/
 .stylelintrc
 .eslintrc
...
```

**Comment by shinnn** [comment]
Restructure the repository more natural way, for example either of the following:

* Install `stylelint-config-recommended-scss` right under the `workdir`.
* Move `.stylelintrc` from `workdir` to `workdir/frontend/pageA`.
* Add `.stylelintrc` which extends `../../.stylelintrc` to `workdir/frontend/pageA`.

I won't add `configBasedir` support to promote intuitive directory structure.
