### ISSUE TITLE
Add support for ignoring files

### ISSUE THREAD

**Issue by sdurnov** [shinnn/vscode-stylelint#151]
Right now, it runs agains all files and ignores exlude both from stylelint config and .stylelintignore.
It even shows warnings in HTML

**Comment by shinnn** [comment]
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/148

> it runs agains all files

Nah. Read the document before opening new issues.

> ignores exlude both from stylelint config

Nah.

> and .stylelintignore

https://github.com/shinnn/vscode-stylelint/issues/139#issuecomment-365128588
