### ISSUE TITLE
Stylelint errors in markdown files

### ISSUE THREAD

**Issue by mafredri** [shinnn/vscode-stylelint#152]
Since a while back, stylelint has started started listing errors/problems in markdown files.

The only use case for checking markdown I can think of if there exists a code tag of type CSS, outside of that, stylelint has no business linting markdown.

<img width="594" alt="screen shot 2018-03-13 at 12 49 09" src="https://user-images.githubusercontent.com/147409/37337437-f5d3be6e-26bc-11e8-9e51-caa4744824aa.png">

**Comment by mafredri** [comment]
Ah, I see now that this is a dupe of #148.

I had assumed that this was a new issue since there were no open issues regarding the matter. It would be helpful for anyone who runs into this issue if the relevant issue was kept open until fixed (even if it's upstream).

I would appreciate it if markdown support would be disabled until the issue is actually fixed upstream. Personally I have no interest in waiting around for an upstream fix or adding workarounds to my config. For now, stylelint will be uninstalled.

**Comment by shinnn** [comment]
Thanks for taking a lot of time to explain your carelessness and childishness.
