### ISSUE TITLE
add  language identifiers selection config option

### ISSUE THREAD

**Issue by fheidrich** [shinnn/vscode-stylelint#158]
It seems that vscode-stylelint is always enabled for a several  language identifiers (css, html, less, markdown, etc)
I would like to be able select which 'language identifiers' I want  use vscode-stylelint with.

Exactly the same as "eslint.validate" option defined in vscode-eslint
See:
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

In other words, is possible to add a "stylelint.validate" ? Thanks

**Comment by shinnn** [comment]
Thanks for the suggestion, but https://github.com/shinnn/vscode-stylelint/issues/148#issuecomment-370976249 is enough.
