### ISSUE TITLE
[Feature Request] Enable extension only when config is present

### ISSUE THREAD

**Issue by lachieh** [shinnn/vscode-stylelint#159]
Not all projects include stylelint and it would be good to be able to disable linting on these projects if there is no stylelintrc/cosmiconfig present in the workspace directory. This would obviously via a user preference.

Currently, I have to disable this extension per workspace, which creates additional files specific to VSCode which not all the other developers use.

**Comment by shinnn** [comment]
Yes, as you said this extension always validates CSS even when it cannot find any stylelint configuration files. However, in this case stylelint does not report any stylistic issues but only fatal syntax errors. This behavior works fine for me.

Do you mean this extension should report nothing, even syntax errors when no configuration files exist?

**Comment by lachieh** [comment]
Let me do some investigating and get back to you. It was showing style issues for me, but I'll need to do a reduced test case to see if it was just a bug within another plugin.

**Comment by lachieh** [comment]
This is not an issue. I was working in a project with a stylelint property in the package.json.

**Comment by shinnn** [comment]
Glad to hear you found the cause.
