### ISSUE TITLE
Undefined rule "length-zero-no-unit"

### ISSUE THREAD

**Issue by ivancuric** [shinnn/vscode-stylelint#16]
Using `stylelint-config-standard`.
The rule was deprecated: https://github.com/stylelint/stylelint/blob/b1ebde61677799f1a0b3ac33dde75838a31ab67b/src/rules/number-zero-length-no-unit/README.md

**Comment by shinnn** [comment]
Fixed in https://github.com/shinnn/vscode-stylelint/commit/e49808c9e9fb4462f9d2cddebe2d19df3f7cc604.
