### ISSUE TITLE
Lints .md files

### ISSUE THREAD

**Issue by FezVrasta** [shinnn/vscode-stylelint#162]
I get stylelint errors inside `md` files, in `jsx` or `js` codeblocks... Is this expected?

![image](https://user-images.githubusercontent.com/5382443/38196518-dbb132ce-3683-11e8-8a8d-baa18d2c6ae3.png)

**Comment by shinnn** [comment]
Not an issue with this extension. https://github.com/gucong3000/postcss-html/issues/40

**Comment by FezVrasta** [comment]
oh thanks!

**Comment by shinnn** [comment]
Fixed in https://github.com/gucong3000/postcss-html/commit/576772ce3acbb30127197071cead2411ccdcd99f.
