### ISSUE TITLE
styled-components processor produces a warning without `line` property

### ISSUE THREAD

**Issue by nikitaulshin** [shinnn/vscode-stylelint#164]
Hello!

I'm using your awesome plugin to lint styled-components.

O keep getting a VScode' error saying `TypeError: `line` property of a stylelint warning must be a number, but it was undefined. at stylelintWarningToVscodeDiagnostic`.

Do you have any suggestions how to fix this?

Thanks!

**Comment by shinnn** [comment]
Not an issue with this extension. https://github.com/styled-components/stylelint-processor-styled-components/issues/178
