### ISSUE TITLE
stylelint on *.vue seems don't work when update to 0.36.0

### ISSUE THREAD

**Issue by c446984928** [shinnn/vscode-stylelint#165]
when change *.vue to *.css, It will work, just like the image bellow:
![image](https://user-images.githubusercontent.com/6151965/38455115-a803490a-3aa5-11e8-947e-5bdb496437ac.png)

But if use it's original ext, *.vue, style lint will not work

![image](https://user-images.githubusercontent.com/6151965/38455127-ecc4bae2-3aa5-11e8-9744-977489e976be.png)

thanks

**Comment by shinnn** [comment]
Not an issue with this extension itself. Submit a new issue to https://github.com/stylelint/stylelint/issues with more helpful information.
