### ISSUE TITLE
stylelint doesn't work for styled-components

### ISSUE THREAD

**Issue by vkhitev** [shinnn/vscode-stylelint#166]
Error highlighting works well while linting .css files, but it recognizes only the `no-eol-whitespace` rule while linting styled-components.

Extension version: 0.36.0

dependencies
```json
"styled-components": "^3.2.5",
"stylelint": "^9.1.3",
"stylelint-config-standard": "^18.2.0",
"stylelint-config-styled-components": "^0.1.1",
"stylelint-processor-styled-components": "^1.3.1"
```

.stylelintrc.json
```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": ["stylelint-config-standard", "stylelint-config-styled-components"]
}
```

index.js
```js
import styled from 'styled-components';

const foo = styled('div')`
  rule: 1;

  & > x {
  }
`;
```

![image](https://user-images.githubusercontent.com/15079627/38466864-276c4c9a-3b38-11e8-9718-08aa0c1b3169.png)

![image](https://user-images.githubusercontent.com/15079627/38466874-433fcbc2-3b38-11e8-8fa8-006bc6930f38.png)

![image](https://user-images.githubusercontent.com/15079627/38466889-8f31ac62-3b38-11e8-8393-a17572e51d81.png)

**Comment by shinnn** [comment]
Not an issue with this extension itself. Submit a new issue to https://github.com/stylelint/stylelint/issues with more helpful information.
