### ISSUE TITLE
.stylelintignore is not respected

### ISSUE THREAD

**Issue by jrusse27** [shinnn/vscode-stylelint#167]
I'm using stylelint@9.2.0 installed globally with vscode-stylelint@0.20.4, and for me the .stylelintignore file is not being respected. If i use the stylelint CLI it is respected but the vscode plugin does not seem to do this correctly (for example this behaviour works correctly with eslint/vscode-eslint).

**Comment by shinnn** [comment]
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/139.
