### ISSUE TITLE
stylelint-processor-styled-components don't work

### ISSUE THREAD

**Issue by livemirsi** [shinnn/vscode-stylelint#168]
Hello. Thank for extension) But i have little bit problems) 
"stylelint": "^9.1.0",
"stylelint-config-standard": "^18.2.0",
"stylelint-config-styled-components": "^0.1.1",
"stylelint-processor-styled-components": "^1.3.1"
vscode version 1.22.1

I see errors  when i run command ./node_modules/.bin/stylelint 'src/**/*.jsx', but in vscode not show error

**Comment by shinnn** [comment]
It's an issue with the upstream project. https://github.com/stylelint/stylelint/issues/3252
