### ISSUE TITLE
CssSyntaxError with templating language in <style> tag

### ISSUE THREAD

**Issue by psybork** [shinnn/vscode-stylelint#169]
Hey,

I've been using this plugin for a while and I can't make this extension disregard the fact that I'm using the templating language Jinja in  an HTML file.

This is my inline style in the head section
![image](https://user-images.githubusercontent.com/22729436/38586796-1a31ede2-3d17-11e8-92ce-5eb939933fcd.png)

Besides disabling this extension, is there anyway to disregard that rule ?

**Comment by shinnn** [comment]
Not an issue with this extension itself. Submit a new issue to https://github.com/stylelint/stylelint/issues with more helpful information.
