### ISSUE TITLE
Update: Please support CSS property: speak

### ISSUE THREAD

**Issue by tommai78101** [shinnn/vscode-stylelint#176]
This is an update to #175. 

Source: https://github.com/stylelint/stylelint/issues/3285#issuecomment-385459809

In the upstream, they said `speak` is part of `known-css-properties`, and suggested it may be an issue with the VS Code.

Thanks anyway, will be reporting over to VS Code.

**Comment by shinnn** [comment]
> In the upstream, they said speak is part of known-css-properties, and suggested it may be an issue with the VS Code.

If you mean the stylelint team by "they", no.

> will be reporting over to VS Code.

No thanks. Please use an appropriate issue tracker.
