### ISSUE TITLE
Not working with *.tsx Files and Syntax set to typescriptreact

### ISSUE THREAD

**Issue by marvwhere** [shinnn/vscode-stylelint#177]
Hey there,

thanks for this great plugin, i having a small issue, and can't get it resolved. i read through a lot of issues, and the code here and stylelint itself 

My Problem: stylelint is working fine in the shell (zsh) even with my tsx files. But in vscode i do not get any linting errors. if i switch the "Language Mode" of my tsx file to "scss" it is working fine. And the Errors are showing up.

Yes i have stylelint-processor-styled-components - Here my complete .stylelintrc

    {
      "processors": ["stylelint-processor-styled-components"],
      "plugins": ["stylelint-order"],
      "extends": [
        "stylelint-config-standard",
        "stylelint-config-styled-components",
        "./stylelint-property-order.json"
    ],
      "rules": {
        "value-list-max-empty-lines": null,
        "declaration-colon-newline-after": null,
        "length-zero-no-unit": null,
        "max-empty-lines": null
      },
      "syntax": "scss"
    }

If i switch back to "typescriptreact" Language, the console is opening up with

`Cannot read property 'languageId' of undefined
TypeError: Cannot read property 'languageId' of undefined
    at getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/out/cssServerMain.js:83:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/out/cssServerMain.js:245:16
    at Immediate.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/out/utils/runner.js:30:34)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

Any Ideas?

**Comment by shinnn** [comment]
> `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/out/cssServerMain.js:83:44`

Not an issue with this extension. This extension is `vscode-stylelint`.
