### ISSUE TITLE
Update documentation to mention no support for .stylelintignore 

### ISSUE THREAD

**Issue by row1** [shinnn/vscode-stylelint#179]
Hi,

You closed my issue #178 about  stylelintignore not working as a duplicate. It seems like a few people have raised the same issue, so perhaps instead of closing the issue, you could leave one of these open with an explanation or add it as a known issue in the README?

**Comment by shinnn** [comment]
Thanks for the suggestion, but it's not so hard for me to close duplicate issues every time.

**Comment by row1** [comment]
Sure, but that's not my point. By default when people search for issues it only searches for open issues and not closed ones. So it would be helpful for users like myself to see something in the README or an open issue about this with a tag like 'on-hold' or 'known-issue'. Cheers.
