### ISSUE TITLE
error default config

### ISSUE THREAD

**Issue by ccbikai** [shinnn/vscode-stylelint#18]
![image](https://cloud.githubusercontent.com/assets/2959393/16369790/ccd8b9ec-3c6c-11e6-8c7e-1f5b7d354ffa.png)

![image](https://cloud.githubusercontent.com/assets/2959393/16369806/eea6e71a-3c6c-11e6-991e-3423699fd496.png)

**Comment by shinnn** [comment]
Thanks for the report. Fixed in v0.10.3.
