### ISSUE TITLE
Usage with package.json

### ISSUE THREAD

**Issue by sobolevn** [shinnn/vscode-stylelint#180]
Hi, I have not found any information in the docs about using this plugin with configuration specified right inside the `package.json`.

Here's how my setup looks like: https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json#L33

By default this configuration is not loaded. I have double checked that.

**Comment by shinnn** [comment]
> I have not found any information in the docs about using this plugin with configuration specified right inside the `package.json`.

Of course. It's out of the scope of this repository.

**Comment by sobolevn** [comment]
@shinnn sorry, but your answer was nor helpful, nor informative. 

I do not understand why this is out of scope of your project.

There are several ways to configure `stylelint` and specifying configuration inside `package.json` is one of them. Here's the pull request when this feature was originally introduced in 2015: https://github.com/stylelint/stylelint/issues/490

So, there are two possible issues here:
1. `package.json` is ignored and configuration is not loaded
2. I am missing something obvious that could be pointed out and fixed in the docs (that's why docs exist in the first place)

Waiting for your response, even issue had been closed already.
Thanks!
