### ISSUE TITLE
Add VSIX file to each Github release

### ISSUE THREAD

**Issue by txava** [shinnn/vscode-stylelint#184]
I realize you release regularly, but do not publish the VSIX file here on GitHub. If it isn't too much trouble, do you mind publishing that file to GitHub too? I ask because we think your extension is superb, and we'd like to add it to one of our CodeMix extension packs.

Having a VSIX file would make inclusion much easier, but if that's not possible, would you mind tagging each release?

Thank you, and keep up the great work!
You can find out more about CodeMix here: https://www.genuitec.com/box/products/codemix/

**Comment by shinnn** [comment]
If you create an automated extension publishing tool like [np](https://github.com/sindresorhus/np) for npm package, I'll happily use it.

**Comment by txava** [comment]
Hey Shinosuke,

Have you checked this project? [release-it](https://github.com/webpro/release-it),
I think you could use the afterReleaseCommand [hook](https://github.com/webpro/release-it#-command-hooks) to run *vsce* and publish the package.

**Comment by shinnn** [comment]
Not enough. Check what `np` does. Similar level of quality is required.

**Comment by shinnn** [comment]
It seems that no one seems to be interesting in fixing this issue.
