### ISSUE TITLE
Error: Undefined rule font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by stuartZhang** [shinnn/vscode-stylelint#187]
Because the introduced  `stylelint` version is too low to corporate with the stylelint-configuration npm module "stylelint-config-standard".

Along with the latest "stylelint-config-standard", "Error: Undefined rule font-family-no-missing-generic-family-keyword" happens.

Please you upgrade the `stylelint` to v8.3.0+

**Comment by shinnn** [comment]
> Because the introduced `stylelint` version is too low

No.

```console
$ npm ls stylelint
stylelint@0.36.2 /Users/shinnn/github/vscode-stylelint
└─┬ stylelint-vscode@7.0.0-3
  └── stylelint@9.2.1  (github:stylelint/stylelint#ecd7c0a89ef3d0c164770883852b3574a013144e)
```
