### ISSUE TITLE
Cannot read property 'objectExpression'

### ISSUE THREAD

**Issue by sampotts** [shinnn/vscode-stylelint#188]
I'm running latest Stylelint and latest plugins. Not 100% sure when we started seeing this but it only seems to happen on JavaScript files. 

Here's our config:

```json
{
    "extends": ["stylelint-config-recommended", "stylelint-config-prettier"],
    "rules": {
        "indentation": 4,
        "string-quotes": "single"
    }
}
```

Here's the error:

![image](https://user-images.githubusercontent.com/719092/40343154-da755708-5dd1-11e8-935d-075311b2eded.png)

**Comment by shinnn** [comment]
@sampotts Can you show me your JavaScript file that causes this error?

**Comment by shinnn** [comment]
Confirmed, but it's an upstream issue. https://github.com/gucong3000/postcss-jsx/issues/8

**Comment by sampotts** [comment]
Thanks. I'll keep an eye on that issue.
