### ISSUE TITLE
In non-style file: TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach 

### ISSUE THREAD

**Issue by ethancfchen** [shinnn/vscode-stylelint#190]
While I edit my JS file, I keep receive the notification from stylelint:

```
TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach 
```

Add `**/*.js` in my `.stylelintignore` file is not working.

**Comment by shinnn** [comment]
Exact duplicate of https://github.com/shinnn/vscode-stylelint/issues/189.
