### ISSUE TITLE
Update required to fix #188

### ISSUE THREAD

**Issue by sampotts** [shinnn/vscode-stylelint#199]
I can't comment on the original issue but can the plugin be updated to resolve the upstream issue mentioned on the above issue:
https://github.com/shinnn/vscode-stylelint/issues/188

Since you closed the other issue (for whatever reason, it's still an issue), it *does* do it for any JavaScript file contrary to your comments.

**Comment by jzaefferer** [comment]
https://github.com/gucong3000/postcss-jsx/issues/8 was fixed 5 hours ago. I'm disabling this extension until there's an update available.

**Comment by sampotts** [comment]
Yep I’ve had to do the same. It was driving me insane constantly popping up on any JS file I edited. I’m glad I’m not alone!

**Comment by shinnn** [comment]
Further discussion goes to https://github.com/shinnn/stylelint-vscode/pull/10.
