### ISSUE TITLE
Why does this error occur when upgrading a new version?

### ISSUE THREAD

**Issue by a378199326** [shinnn/vscode-stylelint#201]
TypeError: Cannot read property 'objectExpression' of undefined at path.get.forEach (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:123:11) at Array.forEach (native) at enter (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/postcss-jsx/extract.js:114:28) at NodePath._call (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:65:20) at NodePath.call (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:36:14) at NodePath.visit (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/path/context.js:100:12) at TraversalContext.visitQueue (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/context.js:142:16) at TraversalContext.visitSingle (/Users/liujinjin/.vscode/extensions/shinnn.stylelint-

**Comment by dlandis** [comment]
I am getting that error after upgrading to version `0.36.2`. Also getting similar error:
```
TypeError: Cannot read property 'file' of undefined     at Scope.checkBlockScopedCollisions (/Users/dlandis/.vscode/extensions/shinnn.stylelint-0.36.2/node_modules/@babel/traverse/lib/scope/index.js:358:21)    
```
Basically error is thrown after every keypress.

**Comment by mehas** [comment]
Duplicate of #188

**Comment by shinnn** [comment]
Duplicate of https://github.com/shinnn/vscode-stylelint/issues/198
