### ISSUE TITLE
Latest version suddenly lints my .js files oO

### ISSUE THREAD

**Issue by rvetere** [shinnn/vscode-stylelint#205]
I don't know exactly when this started, but suddenly my stylelint plugin in vscode is linting my javascript files too, which is very annoying -.-

![alt text](https://i.imgur.com/bcGvcah.jpg "Issue pic")

i don't see any config setting leading to this, to fix it or something... i can only disable it entirely..

**Comment by alxmiron** [comment]
Reproduced for me on VSCode 1.23.1, vscode-stylelint 0.36.2

**Comment by shinnn** [comment]
It's an expected behavior.
