### ISSUE TITLE
postcss-syntax doesn't consider *.overrides as LESS files

### ISSUE THREAD

**Issue by sneridagh** [shinnn/vscode-stylelint#208]
I use SemanticUI in my projects and I would like to include the extension ".overrides" as a less file, and that stylelint (and prettier stylelint integration) works with it. I been looking into that, but I couldn't make it work, even if I have the extension mapped as a less file in vscode.

Is there any way to do it?

Thanks.

**Comment by sneridagh** [comment]
Ok, it seems I've found a workaround, the console was showing one error each time I save:

Cannot find module 'postcss-overrides'

Here's the workaround: I've duplicated the module `postcss-less` and named it `postcss-overrides`. :tada: It started to work.

It would be great if the plugin could allow the mapping of an extension to a syntax in vscode. It seems that the command line allows you to do that with the `files/glob` parameter.

**Comment by shinnn** [comment]
It's not an issue with vscode-stylelint itself and I'm not interested in including a workaround for it.

Submit a patch to the upstream project https://github.com/gucong3000/postcss-syntax/pulls to include `.overrides` in https://github.com/gucong3000/postcss-syntax/blob/99df76bd14a57ce64daa68e9b63229f7cd92a906/index.js#L8.
