### ISSUE TITLE
Need changelog

### ISSUE THREAD

**Issue by MartynasZilinskas** [shinnn/vscode-stylelint#21]
It would be awesome to have changelog. To follow what changes in the newest update were made.

**Comment by GiedriusGrabauskas** [comment]
:+1:

**Comment by mrmlnc** [comment]
Or better yet, if you will use GitHub releases.

**Comment by shinnn** [comment]
Git is a great changelog.

**Comment by GiedriusGrabauskas** [comment]
Use tags...
