### ISSUE TITLE
Cannot read property 'file' of undefined at Scope.checkBlockScopedCollisions 

### ISSUE THREAD

**Issue by sshmyg** [shinnn/vscode-stylelint#210]
Hi, could you help find out whats wrong.

Reproduce:
1. Open file with Javascript (babel) syntax.
2. Duplicate import statement _(non-SSL URL deleted by @shinnn)_
3. Get such an error.

`
TypeError: Cannot read property 'file' of undefined at Scope.checkBlockScopedCollisions (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:347:21) at Scope.registerBinding (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:506:16) at Scope.registerDeclaration (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:454:14) at Object.Declaration (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/scope/index.js:125:12) at NodePath._call (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/path/context.js:53:20) at NodePath.call (/Users/xxx/.vscode/extensions/shinnn.stylelint-0.36.3/node_modules/@babel/traverse/lib/path/context.js:40:17) at NodePath.visit (/Users/xxx/.vscode/extens...
`

osx 10.13.4
vs code 1.23.1
node 10.3.0

Thank you.

**Comment by shinnn** [comment]
1. Don't include non-SSL URLs in the issue description. I never open them.
2. This doesn't seem to be an issue directly related to this extension. Read the stack trace more carefully, detect the actual cause and submit a new issue to more proper repo. I guess [postcss-jsx](https://github.com/gucong3000/postcss-jsx) throws this error.
