### ISSUE TITLE
`ignoreFiles` not being honoured.

### ISSUE THREAD

**Issue by marbuser** [shinnn/vscode-stylelint#218]
I have stylelint setup so that it only handles CSS/SCSS.
`stylelint.config.js`
```
module.exports = {
  plugins: [
    'stylelint-scss',
  ],
  extends: [
    'stylelint-config-idiomatic-order',
    './node_modules/prettier-stylelint/config.js',
    'stylelint-config-standard',
  ],
  ignoreFiles: '**/*.{vue, html, js}',
};
```

However, in files like for example; `stylelint.config.js`, or `.eslintrc.js`, it still lints and gives really annoying messages.
![image](https://user-images.githubusercontent.com/34422459/41529238-05e239a8-731f-11e8-9cc5-aa4d72d40c70.png)

I'm unsure if this is a bug, or if it's just something stupid I'm doing on my end, but some help would be greatly appreciated. :)

An extra question I wanted to ask is when working with Vue files, is it possible to restrict stylelint to only work on the style tagged sections of the template rather than the whole thing?

**Comment by shinnn** [comment]
`**/*.{vue, html, js}` doesn't match neither `stylelint.config.js` nor `.eslintrc.js`.

```js
const minimatch = require('minimatch');

minimatch('.eslintrc.js', '**/*.{vue, html, js}'); //=> false
minimatch('stylelint.config.js', '**/*.{vue, html, js}'); //=> false
```

Submit a question to https://stackoverflow.com or https://github.com/isaacs/minimatch/issues if you want to know a correct glob pattern.

> is it possible to restrict stylelint to only work on the style tagged sections of the template rather than the whole thing?

[stylelint](https://github.com/stylelint/stylelint) should do so. If it doesn't, post a new issue to https://github.com/stylelint/stylelint/issues.
