### ISSUE TITLE
false positive for no-missing-end-of-source-newline in html files

### ISSUE THREAD

**Issue by johnbendi** [shinnn/vscode-stylelint#230]
![screenshot from 2018-07-02 13-55-32](https://user-images.githubusercontent.com/1025834/42165348-bd71d4c6-7dff-11e8-8535-699c18382a42.png)

My current workaround is to add `"ignoreFiles": "**/*.html"` to `stylelint.configOverrides` in settings file.

**Comment by shinnn** [comment]
Not an issue with this extension. Ask stylelint maintainers to reopen https://github.com/stylelint/stylelint/issues/3410. 

They said https://github.com/stylelint/stylelint/issues/3410#issuecomment-399658964:

> It's the responsibility of the user to configure stylelint accordingly

but of course it's not.

**Comment by shinnn** [comment]
Fixed in https://github.com/stylelint/stylelint/commit/83229d53d39e1379997d779aa06b45a8ddc7fc8b.
