### ISSUE TITLE
Document how to turn off validation for a specific file type in the README

### ISSUE THREAD

**Issue by thibaudcolas** [shinnn/vscode-stylelint#237]
I was looking for a way to prevent this extension from trying to validate JSX files. This seems to be a very common request in the issues (https://github.com/shinnn/vscode-stylelint/issues?q=is%3Aissue+is%3Aclosed+label%3Aduplicate). Would it be possible to document this directly in the README, instead of having to resort to the issue tracker to find the answer?

I know that technically `ignoreFiles` will be set with `stylelint.configOverrides`, and that's documented, but it seems common enough of a request to warrant being documented.

---

Additionally, I find it pretty hard to find information about existing issues because of how you mark things as duplicate. Take for example this "turn off validation" scenario – I searched for https://github.com/shinnn/vscode-stylelint/issues?q=is%3Aissue+validation+is%3Aclosed in the issue tracker, and clicked on the first result: #234, which is marked as a duplicate of #233, which itself is marked as duplicate of #231, which itself is marked as duplicate of  #222, which is marked as duplicate of #221, which points to #222, and then #173, and finally https://github.com/shinnn/vscode-stylelint/issues/148#issuecomment-370976249.

Unfortunately GitHub doesn't have a way to navigate straight to the root issue (#148) – could you instead mark future issues as duplicates of that one? 

I had the same issue trying to understand why `.stylelintignore` wasn't taken into account, found #178,  which goes to #167, then #139, then #132, then #101. Couldn't they all point to #101 instead? And additionally potentially document this in the README as well, since even if it's not technically an issue with the extension, people using the extension run into this frequently enough.

---

I'm happy to submit a PR for either of those things if you think that's a good idea.

**Comment by mliq** [comment]
I have set styleLint to ignore all javascript files and I still get the error.

**Comment by shinnn** [comment]
I assume why users want to exclude specific file types from the validation target is that stylelint doesn't correctly parse them and throws errors.

So, contribute [stylelint](https://github.com/stylelint/stylelint) project to fix its bug then you'll never need to set `ignoreFiles` option, to say nothing of documentation update as @thibaudcolas requests.

**Comment by shinnn** [comment]
> I find it pretty hard to find information about existing issues [...]

@thibaudcolas You're misjudging the true nature of the problem. Who've really messed the issue tracker is not the project maintainer but people who submits duplicate issues incorrigibly. If they checked the existing issues before opening a new one in the first place, what you're suffering from didn't happen.

**Comment by shinnn** [comment]
@mliq Not a vscode-stylelint issue.
