### ISSUE TITLE
Lack of documentation for specifying a custom config file

### ISSUE THREAD

**Issue by sebastian-nowak** [shinnn/vscode-stylelint#242]
Hello @shinnn,

(Followup of https://github.com/shinnn/vscode-stylelint/issues/109, https://github.com/shinnn/vscode-stylelint/issues/241, https://github.com/shinnn/vscode-stylelint/issues/97, https://github.com/shinnn/vscode-stylelint/issues/57)

First of all, it really sucks that you're locking all of the tickets before giving anyone a chance to answer.

The **stylelint** docs are the last place someone would check when trying to configure an **external plugin**. The amount of feature requests for `configFile` support clearly shows that it has to be explicitly listed in *your* docs. You made a decision not to support `configFile` explicitly - that's fine, but please, at least make it clear in the README.

Adding it takes just a moment and it'll save everyone lots of time.

Regards,
Sebastian

**Comment by shinnn** [comment]
> The stylelint docs are the last place someone would check when trying to configure an external plugin.

Simply no.
