### ISSUE TITLE
Not using ~/.stylelintrc.yml

### ISSUE THREAD

**Issue by rightaway** [shinnn/vscode-stylelint#244]
The default configuration files specified in https://stylelint.io/user-guide/configuration/#loading-the-configuration-object aren't being used. I have `~/.stylelintrc.yml` (home directory) and it isn't getting picked up. But when I run the stylelint cli it works.

**Comment by shinnn** [comment]
It works.

![image](https://user-images.githubusercontent.com/1131567/45265912-bbdcd380-b48d-11e8-8d86-117075c804ee.png)
