### ISSUE TITLE
Ability to disable extension in settings.json

### ISSUE THREAD

**Issue by c-bandy** [shinnn/vscode-stylelint#248]
In some cases you may want to disable the extension for specific projects to avoid errors in code where linting is not applicable. This can be done on project or global level in extensions such as ESLint, but this is missing for the stylelint extension.

Can a setting be added to `settings.json` that lets you disable the extension?

**Comment by shinnn** [comment]
> this is missing for the stylelint extension.

No.

**Comment by c-bandy** [comment]
Having this set to false does not completely disable the extension. It does what the documentation says, disables it for CSS, SCSS and LESS. The extension still outputs errors on HTML files.

```javascript
// Control whether stylelint is enabled for CSS/SCSS/Less files or not.
"stylelint.enable": true
```

With the setting set to false I get errors in Visual Studio Code:

<img width="407" alt="screenshot 2018-09-26 at 16 07 53" src="https://user-images.githubusercontent.com/31383109/46085451-5f282b00-c1a6-11e8-97eb-3c9f4cc8efef.png">

**Comment by shinnn** [comment]
> `[doctype-first]`

What you've posted here is totally unrelated to vscode-stylelint. Every diagnostic reported by this extension starts with `[stylelint]`.
