### ISSUE TITLE
Lints *.svg files by default

### ISSUE THREAD

**Issue by mserajnik** [shinnn/vscode-stylelint#252]
See screenshot:

<img width="1068" alt="screenshot 2018-11-14 at 09 24 50" src="https://user-images.githubusercontent.com/28833155/48469445-322fe600-e7ef-11e8-8cbc-710667b56ae4.png">

It does this for every `*.svg` file in the project. Using default settings.

**Edit:** Or is this a feature? The readme doesn't mention `*.svg` files.

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/tree/dc4fba7d4ef1effec2108d0a2d55c792e0577bf7#usage

> stylelint automatically validates documents with these __[language identifiers](https://code.visualstudio.com/docs/languages/overview#_language-id)__
