### ISSUE TITLE
Some users don't know how to ignore specific files

### ISSUE THREAD

**Issue by garrettw** [shinnn/vscode-stylelint#259]
It would really be helpful if there was a config option to allow stylelint to skip linting files that are very large -- say if the filesize is above a certain amount, or if linting takes longer than a certain amount of time.
Sometimes I encounter large CSS files on sites not built with Sass, and linting slows down VS Code such that saving the file is delayed, and the Git sidebar takes f o r e v e r to update (if it does anything at all) -- this is a definite inconvenience.

**Comment by shinnn** [comment]
You can achieve this by using the already existing stylelint settings.

> takes f o r e v e r
> definite inconvenience

In a technical discussion please describe what happens more precisely and less emotively. No programs run f o r e v e r ©︎ Garrett W.
