### ISSUE TITLE
Update to stylelint >= v9.10.0

### ISSUE THREAD

**Issue by chalkygames123** [shinnn/vscode-stylelint#261]
Recently stylelint has introduced new `function-calc-no-invalid` rule in v9.10.0, but the latest extension cannot recognize that rule. Any workaround?

**Comment by SimonSimCity** [comment]
It would also fix https://github.com/stylelint/stylelint/issues/3807 which I previously posted here: https://github.com/shinnn/vscode-stylelint/issues/253

**Comment by shinnn** [comment]
Fixed in https://github.com/shinnn/vscode-stylelint/commit/70cedb6fda49329d3294b44d86c35345de865c21.

> Any workaround?

@chalkygames123 Modify files in your locally installed vscode-stylelint.

**Comment by chalkygames123** [comment]
@shinnn Thanks!
