### ISSUE TITLE
Duplicate errors in tooltip

### ISSUE THREAD

**Issue by devinrhode2** [shinnn/vscode-stylelint#262]
I have applied these recommended settings in my vscode user config:
```
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
```
But as you can see in this screenshot, I'm getting duplicate errors in this tooltip:
<img width="756" alt="screen shot 2019-01-30 at 4 09 45 pm" src="https://user-images.githubusercontent.com/539816/52016895-62f8f080-24ab-11e9-9c1b-3095cc490fe8.png">

I'm using the latest version of vscode on mac os high sierra

**Comment by shinnn** [comment]
No duplicates.

> :nth-child __(1)__
> :nth-child __(2)__

In the first place, this is not a question about vscode-stylelint but about the upstream project stylelint. Follow https://github.com/stylelint/stylelint#need-help if you want further support.
