### ISSUE TITLE
Different behavior than CLI stylelint

### ISSUE THREAD

**Issue by griest024** [shinnn/vscode-stylelint#274]
I think this is caused by the extension not picking up on my config file but I'm not sure. I have a `.stylelintrc.js` config file in my workspace root. Stylelint picks up on it just fine, both as a webpack plugin and from the command line, without pointing it to the config. FWIW my CLI command is `npx stylelint app/assets/styles/main.pcss`.

The extension is throwing errors where the CLI version is throwing none. The best solution seems to be to add an option to use the NPM packaged stylelint which should ensure identical behavior.

**Comment by shinnn** [comment]
Provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by shinnn** [comment]
@griest024 As [you called others "entitled idiots"](https://github.com/shinnn/vscode-stylelint/issues/270#issuecomment-506043087), of course I expect you to submit a good issue that doesn't bother the maintainer as much as possible ― provides enough information, doesn't leave maintainers guessing and again, has a minimal reproducible example.

**Comment by shinnn** [comment]
Closing as the issue author makes almost no effort to solve the problem.
