### ISSUE TITLE
extend stylelint-config-standard undefined rules

### ISSUE THREAD

**Issue by abrcdf1023** [shinnn/vscode-stylelint#28]
English is not my native language; please excuse typing errors.

Sorry about my unclear question,I can read something but write is difficult to me.

This is my question.

I try to use init stylelint and this is my config

`{ 
"extends": "stylelint-config-standard", 
"rules": { ... }
 `

And then

> npm i stylelint-config-standard --save-dev

Restart my vscode

vscode will show error etc.

stylelint: Undefined rule "declaration-block-no-redundant-longhand-properties"

All rules below is undefined

declaration-block-no-redundant-longhand-properties
media-feature-name-no-unknown
selector-descendant-combinator-no-non-space
value-list-max-empty-lines

If i comont out these rules , it's work,so i am not sure is because version or i make something wrong?

**_stylelint-version-0.14.4_**

**Comment by ivancuric** [comment]
Needs an update. Why aren't you using the global or local npm module?

**Comment by abrcdf1023** [comment]
You are so right , i will use local npm module.

But i am a bit confused about vscode-plugin , it different with npm module?

I try to uninstall vscode-plugin and linter is not working.

2016-08-29 23:08 GMT+08:00 Shinnosuke Watanabe <notifications@github.com>:
