### ISSUE TITLE
Add LESS parser support

### ISSUE THREAD

**Issue by patsissons** [shinnn/vscode-stylelint#3]
This is dependent on `stylelint` getting LESS support. I have opened an [issue](https://github.com/stylelint/stylelint/issues/810) over there for this already. Seems like the code changer here would be relatively easy. If you think it's worth while doing the work ahead of `stylelint` I can submit a PR any time.

**Comment by patsissons** [comment]
`stylelint` now supports `Less`, so i can whip up a PR for this

**Comment by woble** [comment]
Might as well add PostCSS (.pcss, .postcss) as well then.

**Comment by patsissons** [comment]
Should be easy in a subsequent PR

**Comment by woble** [comment]
I noticed that package.json has some reference to SCSS on line 133. Shouldn't LESS ref be added there as well?

**Comment by patsissons** [comment]
Stylelint should be providing both `postcss-scss` and `postcss-less` itself.

**Comment by shinnn** [comment]
v0.8.0 supports `less` language mode. Thanks, @patsissons.
