### ISSUE TITLE
"Doesn't seem to work for me at Visual Studio Insiders"

### ISSUE THREAD

**Issue by shinnn** [shinnn/vscode-stylelint#30]
> Doesn't seem to work for me at Visual Studio Insiders unfortunately

Posted in [Marketplace Reviews](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint#review-details) by @tinovyatkin, but I cannot find any problems with this plugin while using VS Code Insiders.

@tinovyatkin What do yo mean by "doesn't seem to work"? How can we reproduce the problem you're running into?

**Comment by tinovyatkin** [comment]
I just removed it, updated to the latest build of Insiders and it started working. So, sorry, probably it was not a problem on your side.
It was no errors in Developers Tools and no linting altogether - that what I referred 'doesn't seems to work'.
I've updated review on Marketplace too. Thank you.

**Comment by shinnn** [comment]
> updated to the latest build of Insiders and it started working

Glad to hear that.
