### ISSUE TITLE
How to ignore node_modules

### ISSUE THREAD

**Issue by shahzad-0** [shinnn/vscode-stylelint#31]
Hi,

Can someone please tell me where I need to add the ignoreFiles setting. I've tried putting it in the `package.json` as:

```
"styleLint": {
    "ignoreFiles": "node_modules/"
}
```
However, this doesn't seem to be ignoring the files in the node_modules. 

Any help would be greatly appreciated.

Thanks

**Comment by shinnn** [comment]
> style*L*int

Be more case sensitive.

**Comment by shahzad-0** [comment]
@shinnn Sorry, I don't understand. I have `styleLint`, are you saying it should be `stylelint`?

**Comment by shinnn** [comment]
Read https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md.

**Comment by shahzad-0** [comment]
@shinnn thanks for clarifying. I'm still having difficulty trying to ignore the files. I'm using the following:

```
"stylelint": {
    "ignoreFiles": "/node_modules/**/*.css"
 }
```
I still see errors and warnings from css files under node_modules.

**Comment by shinnn** [comment]
Leading `/` indicates the root directory.

**Comment by nonameolsson** [comment]
Hi!
I've tried to follow the instructions. This is my `.stylelintrc`-file: http://pastebin.com/kkf0tsER
I have added:
```
"stylelint": [
  "ignoreFiles": "./node_modules/**/*.css"
]
```

But it still indexes all installed `node_modules`. What am I doing wrong?

**Comment by shinnn** [comment]
`[]` and `{}` are two different things in JSON syntax.
