### ISSUE TITLE
Does not seem to ignore directories

### ISSUE THREAD

**Issue by smlombardi** [shinnn/vscode-stylelint#34]
In some projects, this still shows errors even for files in directories I have added to `.stylelintignore` file:

```
app/bower_components
.sass-cache
node_modules
app/css
.idea
build
.git
```

but I am still getting
![screen shot 2016-10-03 at 3 23 16 pm](https://cloud.githubusercontent.com/assets/835148/19050614/67b0925c-897d-11e6-973f-ccce85ef8d41.jpg)
 errors from files inside `node_modules` and `bower_components`:

**Comment by shinnn** [comment]
The warnings in your screenshot are not produced by stylelint but VSCode's built-in CSS linter.

**Comment by smlombardi** [comment]
So, if I add `"css.validate": false` to my settings.json, stylelint will still function?

**Comment by shinnn** [comment]
No.

![image](https://cloud.githubusercontent.com/assets/1131567/19053548/61344ec2-89f6-11e6-8f2c-03732b0edc61.png)
