### ISSUE TITLE
Constant notifications if there is no config

### ISSUE THREAD

**Issue by kevinSuttle** [shinnn/vscode-stylelint#35]
Even when you explicitly disable stylelint within a file, you are notified of a missing config on every single keystroke.

<img width="1016" alt="app_css_-_vodafone-mobile-asset-management" src="https://cloud.githubusercontent.com/assets/95672/19280513/3457a0d4-8fb4-11e6-9607-7206b43835d8.png">

**Comment by shinnn** [comment]
Thanks for the report, @kevinSuttle. Fixed in vscode-stylelint v0.17.3.
