### ISSUE TITLE
vscode-stylelint ignores my `.stylelintignore` file

### ISSUE THREAD

**Issue by jfmercer** [shinnn/vscode-stylelint#36]
On startup, `vscode-stylelint` ignores my `.stylelintignore` file. However, when I open the file, the plugin reads it & then ignores the specified directories. That is, the plugin works only after I open the ignore file. For debugging, I've tried removing the file & specifying the ignore configuration in `.stylelintrc`, `stylelint.config.js`, & `.stylelintrc.json`, but the problem persisted. 

I'd be happy to write a PR to fix this if you can point me in the direction of a solution.

**Comment by shinnn** [comment]
Can you tell me:

* the path of a file you're trying to ignore
* the path of current directory
* the full content of your `.stylelintignore`
* Visual Studio Code version
* vscode-stylelint version

**Comment by jfmercer** [comment]
- What do you mean by "current directory"? In my CLI, I'm all over the place
- The path to the project root is `$HOME/Code/$PROJECT_ROOT`
- `.stylelintignore` is located in `$PROJECT_ROOT`, that is, `$HOME/Code/$PROJECT_ROOT/.stylelintingore`.
- I've tried three different versions of `.stylelintingore`. Here they are:

```
build/**
bower_components/**
coverage/**
node_modules/**
```

and 

```
build/
bower_components/
coverage/
node_modules/
```

and finally

```
build
bower_components
coverage
node_modules
```

This is VS Code `1.6.0` with vscode-stylelint `0.17.3`.

My node version is `6.8.0`; however, I also had this problem with `6.6.0`. With all three version of `.stylelintingore`, when I open that file, vscode-stylelint _then_ ignores the specified directories.

**Comment by jfmercer** [comment]
I found the problem, and it was on my end. In my `settings.json`, I did not disable VS Code's native css validation. The following, which come straight from the documentation, fixed the issue:

```json
"stylelint.enable": true,
"css.validate": false
```

Note to self: read the docs! 😊
