### ISSUE TITLE
`text-transform` interpreted as `transform2d`

### ISSUE THREAD

**Issue by abea** [shinnn/vscode-stylelint#40]
I have the following SCSS:
```
.nav {
  &-link {
    text-transform: uppercase;
    font-weight: $btn-font-weight;
  }
}
```

and my .stylelintrc settings including:
`"no-unsupported-browser-features": true,`

My file is throwing an error on the text-transform line, `severity: 'Error' message: 'stylelint: Unexpected browser feature "transforms2d" is not supported by Opera Mini all (no-unsupported-browser-features)'`. They're clearly two different attributes and `text-transform` is supported in all browsers as part of CSS2.

This may be a stylelint error, in which case you give me a hint how to find the version of stylelint in use to submit an issue there?

**Comment by shinnn** [comment]
`~/.vscode/extensions/shinnn.stylelint-0.18.2/npm-shrinkwrap.json` on macOS.
