### ISSUE TITLE
Feature Request: Stylus Support

### ISSUE THREAD

**Issue by Lichtjaeger** [shinnn/vscode-stylelint#41]
Hi,

I would love to see this working with [Stylus](http://stylus-lang.com/) too.

**Comment by shinnn** [comment]
This plugin only supports what [the upstream project](https://github.com/stylelint/stylelint) supports. Unfortunately, [stylelint doesn't seem to have Stylus support yet](https://github.com/stylelint/stylelint/issues/674). Help developing [poststylus](https://github.com/seaneking/poststylus) to attain your purpose.
