### ISSUE TITLE
Extension doesn't work on newest version?

### ISSUE THREAD

**Issue by Bigdragon13th** [shinnn/vscode-stylelint#42]
I've update both extension and VSCode to latest:
  - Stylelint: 0.20.0
  - VSCode: 1.7.2

And now this extension is stop working. Do I missing something here? It's working fine yesterday with VSCode 1.7.1 and Stylelint 0.19.

**Comment by shinnn** [comment]
Thanks for the report, @Bigdragon13th. Fixed in vscode-stylelint v0.20.1.

**Comment by Bigdragon13th** [comment]
@shinnn Thank you for your fast fixed. Keep up the good work!! :D
