### ISSUE TITLE
Disable stylelint in sub-directories of project.

### ISSUE THREAD

**Issue by coreybruyere** [shinnn/vscode-stylelint#44]
I have stylelint installed on a local project within VSC and it's linting CSS I have within other sub-directories too (other packages from node_modules). Is there a way to disable other directories from  linting or only specify which directory within a project should go through linting?

**Comment by shinnn** [comment]
Add [`ignoreFiles`](https://github.com/stylelint/stylelint/blob/ab20f8cefeec71e729c6500e7110ae8967d2bbb9/docs/user-guide/configuration.md#ignorefiles) property to your stylelint configuration file.
