### ISSUE TITLE
Does not work with parent folder

### ISSUE THREAD

**Issue by nicolashenry** [shinnn/vscode-stylelint#45]
Using this folder structure :
```
project/
project/src/
project/src/.stylelintrc.json
project/src/css/index.css
```

When I open vscode in "src" folder everything works as expected but if I open vscode in "project" nothing is happening. Note that other linters (like vscode-tslint) seems to be able to work outside the folder containing the configuration file.

**Comment by shinnn** [comment]
This problem is being tracked at https://github.com/shinnn/vscode-stylelint/issues/37.
