### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by softshape** [shinnn/vscode-stylelint#46]
It's not obvious from documentation which set of rules is used by default right after VSC plugin installation?

**Comment by shinnn** [comment]
> It's not obvious

It's *obvious*. The documentation of this repository has a link to the [stylelint configuration guides](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#configuration) that contains what you're looking for.

**Comment by softshape** [comment]
Documentation doesn't describe downloading configs as a required setup step.

**Comment by shinnn** [comment]
> downloading configs as a required setup step

Not required.

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/commit/d02d35a4953d8ee7b3881d1723589f8b210ddf3c
