### ISSUE TITLE
Ignore directories trough VS Code settings?

### ISSUE THREAD

**Issue by sqnkov** [shinnn/vscode-stylelint#50]
@shinnn, Is it possible to ignore my CSS path, beacuse I only use stylelint for SCSS validation?

e.g. - I have the following structure:

```
assets/
    css/
    scss/
```

How can I disable the `css/` folder from being indexed, trough the settings.json file of VSCode?

I found this in the docs, but I don't know how to implement it in VSCode - https://stylelint.io/user-guide/configuration/#ignorefiles

**Comment by shinnn** [comment]
Add `ignoreFiles` property to `stylelint.configOverrides` or `stylelint.config`.
