### ISSUE TITLE
vscode-stylelint does not work in HTML files

### ISSUE THREAD

**Issue by abdonrd** [shinnn/vscode-stylelint#52]
The plugin only works in my `.css` files, and not in my `.html` files.
And it works with the `.html` files if I use the stylelint CLI.

Here is my `.stylelintrc`:

```json
{
  "extends": "stylelint-config-standard",
  "processors": ["stylelint-processor-html"]
}
```

Also, I have installed with my `package.json` the `devDependencies`:

```json
{
  ...
  "devDependencies": {
    ...
    "stylelint": "^7.8.0",
    "stylelint-config-standard": "^16.0.0",
    "stylelint-processor-html": "^1.0.0"
  },
  ...
}
```

And in my settings I have:

```json
{
  "css.validate": false,
  "stylelint.enable": true
}
```

**Comment by abdonrd** [comment]
Friendly ping to @shinnn. 🙂

**Comment by shinnn** [comment]
Fixed via https://github.com/shinnn/vscode-stylelint/commit/9f504667964140336b841a7f7ba55d728488739d

**Comment by abdonrd** [comment]
Thanks! 👏

**Comment by arturparkhisenko** [comment]
@shinnn hi, today with VSCode Version 1.17, Stylelint doesn't working before I'll open any CSS file, then it starts working. Also, I found that line of errors and pointers on them are wrong and it starts linting HTML too (making a lot of errors). Do I need to open a new issue? Really want to help but dunno how) it's important to have that working.

**Comment by shinnn** [comment]
> it starts linting HTML too (making a lot of errors)

Install an appropriate stylelint processor.

> Do I need to open a new issue?

No.

> Really want to help

Not needed. All the HTML-related issues will be resolved if https://github.com/stylelint/stylelint/pull/2975 is landed.

**Comment by pateroski** [comment]
Hi everyone! :)

Similar issue as @arturparkhisenko. Actually with VSCode version 1.20.1 for macOS High Sierra version 10.13.3, after you don't open a `.css` or `.scss` file, vscode-stylelint doesn't lint on `.html` files. 

It would be great to report more info if needed @shinnn.

Thanks so much.

**Comment by shinnn** [comment]
> Actually with VSCode version 1.20.1 for macOS High Sierra version 10.13.3, until you don't open a .css or .scss file

It should have been fixed by https://github.com/shinnn/vscode-stylelint/pull/117 but it's closed.

**Comment by abdonrd** [comment]
@shinnn will you add it to master?

**Comment by abdonrd** [comment]
@shinnn I just send a PR: #142

**Comment by shinnn** [comment]
> I just send a PR: #142

I closed it.
