### ISSUE TITLE
Don't lint the sass directly?

### ISSUE THREAD

**Issue by kinop112365362** [shinnn/vscode-stylelint#53]
it's can lint css file but doesn't work in sass, what should i do ?

**Comment by shinnn** [comment]
> doesn't work in sass

No.

![2017-02-15 19 20 17](https://cloud.githubusercontent.com/assets/1131567/22970032/ec355f58-f3b3-11e6-9af6-21fea372be25.png)

**Comment by kinop112365362** [comment]
it's ok, because the "scss.validate" is true, when i set false, it's good.
