### ISSUE TITLE
unit-whitelist doesn't work

### ISSUE THREAD

**Issue by baixiaoyu2997** [shinnn/vscode-stylelint#54]
`"stylelint.config": {
        "extends": "stylelint-config-standard",
        "rules": {
            "indentation": null,
            "selector-type-no-unknown": [true, {
                "ignoreTypes": ["/^ons-/"]
            }],
            "unit-whitelist":"rpx",//允许使用单位白名单
            "selector-combinator-space-after": "never",
            "selector-combinator-space-before": "never",
            "no-missing-end-of-source-newline": null,
            "rule-non-nested-empty-line-before": null,
            "at-rule-name-case": null
        }
},`

this is my setting.json config,
message: 'Unexpected unknown unit "rpx" (unit-no-unknown)'

**Comment by shinnn** [comment]
It correctly works.

**Comment by baixiaoyu2997** [comment]
i use  stylelint-config-standard,   Once I set unit-whitelist:"rpx", all the units will be given an error，I just want rpx not to be wrong，How can i set it up? plz tell me.

**Comment by shinnn** [comment]
[Join](https://www.w3.org/Consortium/join.html) the discussion about CSS units and propose the new unit `rpx`.

**Comment by baixiaoyu2997** [comment]
I solved myself。
` "unit-no-unknown": [true,{
                "ignoreUnits": ["rpx"]
    }]`
thank you help(help===0)and do not play with me.
