### ISSUE TITLE
vscode-stylelint ignores my "configFile" option

### ISSUE THREAD

**Issue by dr-octopus** [shinnn/vscode-stylelint#55]
I already have a `.stylelintrc.json` referenced in my build process and I'm trying to use the same configuration file in vscode-stylelint, but it seems to ignore the option:

**.stylelintrc.json** (example, not the real one)
<pre>
{
  "rules": {
    "block-no-empty": true
  }
}
</pre>

**settings.json**:
<pre>
{
    "css.validate": false,
    "scss.validate": false,
    "stylelint.enable": true,
    "stylelint.config": {
        "configFile": "config/.stylelintrc.json"
    }
}
</pre>
![stylelint scss](https://cloud.githubusercontent.com/assets/7645409/23089928/f34c44e8-f578-11e6-98da-7a7a7db80200.png)

But, if set the `rules` direct in settings it works fine:
**settings.json**
<pre>
{
    "css.validate": false,
    "scss.validate": false,
    "stylelint.enable": true,
    "stylelint.config": {
          "rules": {
            "block-no-empty": true
          }
    }
}
</pre>
![stylelint scss 2](https://cloud.githubusercontent.com/assets/7645409/23089936/31baf09e-f579-11e6-9a58-163c9fb56f2e.png)

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/blob/465a70463f25e90ce08186e99c632c68e2b0fff5/README.md#stylelintconfig

> ### stylelint.config
> 
> Type: `Object`
> Default: `null`
> 
 > Will be directly passed to [`config`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#config) option.

[Stylelint configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object) doesn't support `configFile` option. Use [`extends`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) option instead.

**Comment by dr-octopus** [comment]
Ops! That's it!

**settings.json:**
<pre>
"stylelint.config": {
    "extends": "./config/.stylelintrc"
}
</pre>

Works perfectly. Thanks for your answer.
