### ISSUE TITLE
Can we get an option to specify a configFile pattern instead?

### ISSUE THREAD

**Issue by rfgamaral** [shinnn/vscode-stylelint#57]
Currently we can specify stylelint configuration files by adding them to the workspace directory following [these rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#configuration).

Personally I don't follow these conventions and try to have all my configuration files under a `config` folder and for stylelint particularly I have something like `config/stylelint.json`. I can't use this extension in it's current state because it won't find my stylelint configuration file.

Can anything be done to improve how stylelint configuration files are read? In other words, could the [`configFile`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#configfile) setting be implemented?

**Comment by michael-yx-wu** [comment]
+1 to this feature request. I too also like having my config files in a `config` folder. 

@rfgamaral a workaround you can do for now is just to symlink your configs to your project root so that this plugin can find them.

**Comment by rfgamaral** [comment]
To add to my suggestion, I also recommend this option to work as a glob (not sure if that's possible) so that if one adds `**/stylelint.json`, it will look for `stylelint.json` (and use the first one) on every folder starting from the root workspace one.

**Comment by elektronik2k5** [comment]
As a workaround, you can do this in your `settings.json`:
```json
  "stylelint.config": {
    "extends": "/absolute/path/to/your/conf/.stylelintrc.json"
  },
```
This could have been better if the property value supported VSCode interpolations like `"window.title"` does (search for it [here](https://code.visualstudio.com/docs/customization/userandworkspace)).

**Comment by shinnn** [comment]
PR welcome. I'm not interesting in this feature though.
