### ISSUE TITLE
Intellisense is broken at random places

### ISSUE THREAD

**Issue by FrogTheFrog** [shinnn/vscode-stylelint#63]
Hey,

so I have noticed that sometimes intellisense does not work in my css files. After some digging I found out that intellisense actually rarely works.

Here are examples of working and broken intellisense:

**Working**
![alt text](http://i.imgur.com/koWOlQ4.png "Working")

**Broken**
![alt text](http://i.imgur.com/ZrSklcO.png "Broken")

**Versions:**
* vscode: 1.10.2
* stylelint: 0.23.0

Here's css file that I have tested it on (forgive me for those tab indents):
```
:host {

	/* works here */

	& #ruleContainer {

		/* works here */

		left: 0;

		/* works here */

		bottom: 0;

		/* doesn't work here */
		
		height: 250px;

		/* doesn't work here */

		background: white;

		/* doesn't work here */

		position: absolute;

		/* doesn't work here */

		overflow: auto;

		/* doesn't work here */

	}

	/* doesn't work here */

	& #colorPicker {

		/* works here */

		overflow: auto;

		/* works here */

	}

	/* doesn't work here */

}
```

**Comment by shinnn** [comment]
Intellisense is not a part of this extension, so the problem comes from from another extension or VSCode itself.
