### ISSUE TITLE
Do I need to have `stylelint` installed in my project to use this plugin?

### ISSUE THREAD

**Issue by svipben** [shinnn/vscode-stylelint#67]
Hello,

Do I need to have `stylelint` installed in my project to use this plugin? Because right now I have `stylelint` installed in my project, but do I need it or plugin is not using it?

As I can see it works without `stylelint` plugin, but maybe it's better to have it installed in project?

Thanks.

**Comment by shinnn** [comment]
No.

**Comment by abdonrd** [comment]
@shinnn but if I have stylelint installed in my project, what version will it use? The plugin version or the project version?

**Comment by shinnn** [comment]
@abdonrd The version bundled in the extension.

**Comment by abdonrd** [comment]
@shinnn Is there an option to use the project version?

**Comment by shinnn** [comment]
@abdonrd No, and I have a definite answer for why not. I'll comment it on shinnn/vscode-stylelint#4 when I have time.

**Comment by abdonrd** [comment]
@shinnn ok! Why is the issue conversation closed? 😕

**Comment by shinnn** [comment]
@abdonrd I don't remember why. I'll reopen it when I comment the answer there.
