### ISSUE TITLE
Does not support /deep/ in Angular Components (cont)

### ISSUE THREAD

**Issue by binarious** [shinnn/vscode-stylelint#68]
I don't know why https://github.com/shinnn/vscode-stylelint/issues/59 is locked, but this issue is now tracked here: https://github.com/stylelint/stylelint/issues/2506. @shinnn maybe you could reference this in the original issue since that's the only good result I found via Google.

**Comment by shinnn** [comment]
Thanks.

**Comment by shinnn** [comment]
https://github.com/stylelint/stylelint/issues/2506#issuecomment-296432321
