### ISSUE TITLE
Autofixing errors

### ISSUE THREAD

**Issue by svipben** [shinnn/vscode-stylelint#69]
Hello,

what do you think about autofixing errors config on save?
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md#autofixing-errors

It will fix errors if I save document like it is right now in ESLint plugin for VS Code.

**Comment by shinnn** [comment]
The new version of stylelint with `--fix` option is not released yet.

**Comment by svipben** [comment]
@shinnn But after release you will include this feature too?

**Comment by shinnn** [comment]
PR welcome. Not very interested though, because `vscode-stylefmt` does almost the same thing.

**Comment by svipben** [comment]
@shinnn I opened an issue in `stylefmt` package about autofixing, if they will add it, then yeah `vscode-stylefmt` will have autofixing.

**Comment by shinnn** [comment]
> I opened an issue in `stylefmt` package about autofixing

❓

**Comment by svipben** [comment]
@shinnn I mean this https://github.com/morishitter/stylefmt/issues/296. It will be very good if they include it after new stylelint release, but if they don't we need to think by adding it here :smile:

**Comment by shinnn** [comment]
You opened "Add autofixing feature" to `stylefmt`?

Um, ah, read the project's readme before opening new Github issues.

**Comment by svipben** [comment]
@shinnn What do you mean? Firstly I opened issue here to include new coming feature to auto fix errors on save, after that I opened issue in `stylefmt`, because they are formatting CSS based on `stylelint` rules, so it will be cool to have auto fixing config before formatting, but yeah more better approach will be add auto fixing here in `stylelint` plugin.
