### ISSUE TITLE
Error: Unexpected "space" found

### ISSUE THREAD

**Issue by svipben** [shinnn/vscode-stylelint#70]
Hello,

I get this error:
`
messageService.ts:126Error: Unexpected "space" found.     at new error (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/processor.js:29:23)     at Parser.error (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:234:15)     at Parser.pseudo (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:362:18)     at Parser.parse (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:551:22)     at Parser.loop (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:519:18)     at new Parser (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:104:21)     at Processor.process (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/processor.js:26:21)     at resolvedNestedSelector.forEach.resolvedSelector (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/rules/selector-max-compound-selectors/index.js:76:55)     at Array.forEach (native)     at rule.selectors.forEach.selector (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/rules/selector-max-compound-selectors/index.js:74:48)e.doShow @ messageService.ts:126
`

I'm using this `.css`:
```
body {
  margin: 0;
  padding: 0;
}

.app {
  text-align: center;
}

.hero {
  background: #222;
  width: 100%;
  height: 150px;
}

.git {
  font-size: xx-large;
  display: inline-block;
  position: relative;
  top: 50%;
  transform: translateY(-50%);
  text-decoration: none;
  color: #ddd;

  &:hover,
  &:active {
    color: white;
  }
}

.content {
  margin: 14px;

  & .large-text {
    font-size: x-large;
  }
}

code {
  background: #eff0f1;
}
```

Try to write `:` symbol, for e.g. `:root` at the top and you will be able to reproduce this error.

**Comment by shinnn** [comment]
Not a vscode-stylelint issue.

**Comment by svipben** [comment]
@shinnn Sorry, opened an issue in https://github.com/postcss/postcss-selector-parser/issues/108.
