### ISSUE TITLE
Config completion for JS files

### ISSUE THREAD

**Issue by OliverJAsh** [shinnn/vscode-stylelint#71]
Is it possible to provide config completion for JS config files i.e. `stylelint.config.js`, like we do for JSON config files?

![image](https://cloud.githubusercontent.com/assets/921609/25847255/3a8df02c-34ad-11e7-94d8-a66f4ea0033e.png)

**Comment by shinnn** [comment]
PR welcome, I'm not very interested in this feature though.

**Comment by shinnn** [comment]
No feedback from anyone.
