### ISSUE TITLE
[Feature Request] AutoFix on Save

### ISSUE THREAD

**Issue by kenisteward** [shinnn/vscode-stylelint#72]
Was just wondering if this was planned to be implemented here.  This linter is like TSLint which already supports autofixOnSave (but it has to be a manual save not an auto save).  Would be nice to have the same thing in here.

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/69

**Comment by shinnn** [comment]
Duplicate of another issue. Use GitHub issue search before opening a new one. https://help.github.com/articles/searching-issues-and-pull-requests/
