### ISSUE TITLE
Error when typing :host selector

### ISSUE THREAD

**Issue by equinusocio** [shinnn/vscode-stylelint#73]
I get an error when typing `:host` selector:
![2017-05-12 11 47 11](https://cloud.githubusercontent.com/assets/10454741/25993017/e10ed36e-3708-11e7-9c9e-83ac110ff7fc.gif)

```
TypeError: Cannot read property '0' of undefined at Parser.decl (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25) at Parser.other (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18) at Parser.loop (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26) at parse (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/
```

**Comment by equinusocio** [comment]
I don't know it this is related to this extension or the PostCSS one:
https://github.com/MhMadHamster/vscode-postcss-language/issues/9

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/66#issuecomment-293020911
