### ISSUE TITLE
Startup error: stylelint not working

### ISSUE THREAD

**Issue by urbantrout** [shinnn/vscode-stylelint#76]
Right after I start VSCode and open a CSS/SCSS file I get the following error message:

`Error at generateError (/Users/harald/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/js-yaml/lib/js-yaml/loader.js:162:10) at throwError (/Users/harald/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/js-yaml/lib/js-yaml/loader.js:168:9) at readFlowCollection (/Users/harald/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/js-yaml/lib/js-yaml/loader.js:690:7) at composeNode (/Users/harald/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/js-yaml/lib/js`

![startup error](https://cloud.githubusercontent.com/assets/10465787/26628180/583a3dc2-45fd-11e7-946b-b83321c11f67.png)

- code-1.12.2
- shinnn.stylelint-0.24.0
- node-6.9.1 || node-8.0.0
- stylelint-7.10.1

**Comment by shinnn** [comment]
I cannot reproduce the problem. As far as i can see, YAML parser throws an error.

**Comment by urbantrout** [comment]
Is not related vscode-stylelint. The error also occurs when using stylelint CLI.

**Comment by urbantrout** [comment]
Fix it. A typo in my .stylelintrc caused the problem.

**Comment by luobotang** [comment]
meet similar problem, I use json type, and I miss a " after prop, like ```"key: null```.
