### ISSUE TITLE
Broken in latest release?

### ISSUE THREAD

**Issue by alexandernanberg** [shinnn/vscode-stylelint#78]
I can't get it to work in the latest version (0.24.1). Worked fine before. 
Any configuration I'm missing?

VS Code 1.12.2
Stylelint 7.10.1

**Comment by paulo2nd** [comment]
cant even install right now

**Comment by maibatsu** [comment]
Same problem, does not see config file.

OS: Ubuntu 16.04.2

VSCODE:
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Stylelint 7.10.1
shinnn.stylelint 0.24.5

**Comment by shinnn** [comment]
Fixed in vscode-stylelint `0.24.8`. Thanks for the report, @alexandernanberg.
