### ISSUE TITLE
Plugin not working in subdirectories

### ISSUE THREAD

**Issue by edwinwright** [shinnn/vscode-stylelint#80]
I have the following project structure and can't get the plugin working when I open VSCode at `ProjectRoot`.
```
ProjectRoot
 |-- OtherDirectories
 |-- ui
   |-- .stylelintrc
   |-- package.json
   |-- node_modules
     |-- stylelint
```
But if I open VSCode so the `ui` directory is the root, it works fine. So I'm assuming that my setup is correct.
```
ui
 |-- .stylelintrc
 |-- package.json
 |-- node_modules
   |-- stylelint
```
I can't restructure the project, is there any way to get this working?

**Comment by shinnn** [comment]
This is a bug of the upstream project. https://github.com/stylelint/stylelint/issues/2450

**Comment by alexeyMohnatkin** [comment]
Should it work now? I've updated stylelint, but the issue still exists

**Comment by shinnn** [comment]
Finally fixed in https://github.com/shinnn/vscode-stylelint/commit/6928ef936df96bb9c062409634f56e5dbd0ad03d. Update vscode-stylelint to v0.29.0.
