### ISSUE TITLE
stylelint: Undefined rule selector-max-type

### ISSUE THREAD

**Issue by jeddy3** [shinnn/vscode-stylelint#83]
I'm getting a `stylelint: Undefined rule selector-max-type` error since introducing that rule to my configuration file.

`selector-max-type`, along with 5 other new rules, [were introduced](https://stylelint.io/CHANGELOG/#7120) in `7.12.0`

Thanks for the excellent plugin btw. I use it every day!

**Comment by shinnn** [comment]
Fixed in v0.26.0. Thanks fro the report, @jeddy3 !

**Comment by jeddy3** [comment]
Thank you for the very quick fix!

I can confirm that `0.26.0` works great, thanks.
