### ISSUE TITLE
Configuration .stylelintrc is not being loaded

### ISSUE THREAD

**Issue by sethstha** [shinnn/vscode-stylelint#84]
Linting is not working here. I guess it must be because of configuration not being loaded.

I have `.stylelintrc` file on the root of my project. While config is set as per documentations. This started occurring from the latest update.

Also, tried adding `"stylelint.config": { "extends": "./.stylelintrc" }` on config and doesn't seems to work.

Also, tried installing stylelint globally and locally, nothing seems to fix it

Can you please tell me what can be the causes. I would like to test more.

Thanks

**Comment by shinnn** [comment]
Create a small Github repository to easily reproduce the problem.

**Comment by sethstha** [comment]
Hey @shinnn 

Here is small repo I created. Can you have a look 
https://github.com/sethstha/stylelint-test

Thanks

**Comment by shinnn** [comment]
Just works fine.

![image](https://user-images.githubusercontent.com/1131567/27948926-8ef62c44-6336-11e7-87dc-e7e54ef5693a.png)

**Comment by sethstha** [comment]
Do you have stylelint installed locally or globally? Isn't there a way to debug this extension?

**Comment by shinnn** [comment]
> Do you have stylelint installed locally or globally?

This extension doesn't use neither locally or globally installed stylelint. It just uses the bundled one.

>  Isn't there a way to debug this extension?

Find a folder where this extension is installed, for example `~/.vscode/extensions/shinnn.stylelint-*` on macOS, and modify `index.js` to print debug log you want.
