### ISSUE TITLE
[Suggestion] Include stylelint-config-standard rules if no configuration file is provided?

### ISSUE THREAD

**Issue by Niichie** [shinnn/vscode-stylelint#85]
I finally got this working on vscode on windows by taking somebody's .stylelintrc file and editing the rules, then placing it in my workspace folder. It is working perfectly, however it took me a very long time to figure it out.

This was not very intuitive as a very new user to vscode, and new to github, and I had to read the documentation for this plugin, and the styelint repo several times to figure out that there was no default config included.

What I was wondering was if there was a way to add an embedded default config file into the plugin, similar to:

HTMLHint (https://github.com/Microsoft/vscode-htmlhint)

And also the Atom linter-stylelint (https://github.com/AtomLinter/linter-stylelint)

What they do is if you don't provide a config file for the plugin, they fallback to the default config which would be this one I think (https://github.com/stylelint/stylelint-config-standard/blob/master/index.js)

I think this would be very useful for new users who can't figure out how to get the linter to work, as it would at least provide a default set of rules, and the plugin would then be plug and play!

Thank you :)

**Comment by dmaisano** [comment]
This seems like a great solution for new users, I as well am new to vscode (atom user) and am reading the [stylelint ](https://github.com/stylelint/stylelint) documentation, trying to get it to work as intended. I am using the plugin mainly to handle linting my PostCSS files which I am having difficulty with. The screenshot shows the error of not having a stylelint config file (such as `.stylelintrc`). For some reason as of today, I have been getting this message saying load document failed, I tried checking the developer tools for more info but it wasn't much help. 

![stylelint](https://user-images.githubusercontent.com/17837521/28653525-0487eba8-725c-11e7-9472-27f6cfb77c24.png)

@Niichie would you be able to share the `.stylelintrc` file you use, I am curious to see if your rules would work for linting regular css in my case :)

**Comment by Niichie** [comment]
@dmaisano, you can copy this into a file in notepad++ and save it as .stylelintrc

Then simply put it in your workspace root folder.

> {
> 	"rules": {
>     "at-rule-empty-line-before": [ "always", {
>       except: [
>         "blockless-after-same-name-blockless",
>         "first-nested",
>       ],
>       ignore: ["after-comment"],
>     } ],
>     "at-rule-name-case": "lower",
>     "at-rule-name-space-after": "always-single-line",
>     "at-rule-semicolon-newline-after": "always",
>     "block-closing-brace-empty-line-before": "never",
>     "block-closing-brace-newline-after": "always",
>     "block-closing-brace-newline-before": "always-multi-line",
>     "block-closing-brace-space-before": "always-single-line",
>     "block-no-empty": true,
>     "block-opening-brace-newline-after": "always-multi-line",
>     "block-opening-brace-space-after": "always-single-line",
>     "block-opening-brace-space-before": "always",
>     "color-hex-case": "lower",
>     "color-hex-length": "short",
>     "color-no-invalid-hex": true,
>     "comment-empty-line-before": [ "always", {
>       except: ["first-nested"],
>       ignore: ["stylelint-commands"],
>     } ],
>     "comment-no-empty": true,
>     "comment-whitespace-inside": "always",
>     "custom-property-empty-line-before": [ "always", {
>       except: [
>         "after-custom-property",
>         "first-nested",
>       ],
>       ignore: [
>         "after-comment",
>         "inside-single-line-block",
>       ],
>     } ],
>     "declaration-bang-space-after": "never",
>     "declaration-bang-space-before": "always",
>     "declaration-block-no-duplicate-properties": [ true, {
>       ignore: ["consecutive-duplicates-with-different-values"],
>     } ],
>     "declaration-block-no-redundant-longhand-properties": true,
>     "declaration-block-no-shorthand-property-overrides": true,
>     "declaration-block-semicolon-newline-after": "always-multi-line",
>     "declaration-block-semicolon-space-after": "always-single-line",
>     "declaration-block-semicolon-space-before": "never",
>     "declaration-block-single-line-max-declarations": 1,
>     "declaration-block-trailing-semicolon": "always",
>     "declaration-colon-newline-after": "always-multi-line",
>     "declaration-colon-space-after": "always-single-line",
>     "declaration-colon-space-before": "never",
>     "declaration-empty-line-before": [ "always", {
>       except: [
>         "after-declaration",
>         "first-nested",
>       ],
>       ignore: [
>         "after-comment",
>         "inside-single-line-block",
>       ],
>     } ],
>     "font-family-no-duplicate-names": true,
>     "function-calc-no-unspaced-operator": true,
>     "function-comma-newline-after": "always-multi-line",
>     "function-comma-space-after": "always-single-line",
>     "function-comma-space-before": "never",
>     "function-linear-gradient-no-nonstandard-direction": true,
>     "function-max-empty-lines": 0,
>     "function-name-case": "lower",
>     "function-parentheses-newline-inside": "always-multi-line",
>     "function-parentheses-space-inside": "never-single-line",
>     "function-whitespace-after": "always",
>     "indentation": 2,
>     "keyframe-declaration-no-important": true,
>     "length-zero-no-unit": true,
>     "max-empty-lines": 1,
>     "media-feature-colon-space-after": "always",
>     "media-feature-colon-space-before": "never",
>     "media-feature-name-case": "lower",
>     "media-feature-name-no-unknown": true,
>     "media-feature-parentheses-space-inside": "never",
>     "media-feature-range-operator-space-after": "always",
>     "media-feature-range-operator-space-before": "always",
>     "media-query-list-comma-newline-after": "always-multi-line",
>     "media-query-list-comma-space-after": "always-single-line",
>     "media-query-list-comma-space-before": "never",
>     "no-empty-source": true,
>     "no-eol-whitespace": true,
>     "no-extra-semicolons": true,
>     "no-invalid-double-slash-comments": true,
>     "no-missing-end-of-source-newline": true,
>     "number-leading-zero": "always",
>     "number-no-trailing-zeros": true,
>     "property-case": "lower",
>     "property-no-unknown": true,
>     "rule-empty-line-before": [ "always-multi-line", {
>       except: ["first-nested"],
>       ignore: ["after-comment"],
>     } ],
>     "selector-attribute-brackets-space-inside": "never",
>     "selector-attribute-operator-space-after": "never",
>     "selector-attribute-operator-space-before": "never",
>     "selector-combinator-space-after": "always",
>     "selector-combinator-space-before": "always",
>     "selector-descendant-combinator-no-non-space": true,
>     "selector-list-comma-newline-after": "always",
>     "selector-list-comma-space-before": "never",
>     "selector-max-empty-lines": 0,
>     "selector-pseudo-class-case": "lower",
>     "selector-pseudo-class-no-unknown": true,
>     "selector-pseudo-class-parentheses-space-inside": "never",
>     "selector-pseudo-element-case": "lower",
>     "selector-pseudo-element-colon-notation": "double",
>     "selector-pseudo-element-no-unknown": true,
>     "selector-type-case": "lower",
>     "selector-type-no-unknown": true,
>     "shorthand-property-no-redundant-values": true,
>     "string-no-newline": true,
>     "unit-case": "lower",
>     "unit-no-unknown": true,
>     "value-list-comma-newline-after": "always-multi-line",
>     "value-list-comma-space-after": "always-single-line",
>     "value-list-comma-space-before": "never",
>     "value-list-max-empty-lines": 0,
>   },
> }
>

**Comment by shinnn** [comment]
It's too weird to get the different lint results depending on whether we use the CLI or VSCode extension.
