### ISSUE TITLE
Doesn't lint .jsx files

### ISSUE THREAD

**Issue by ismay** [shinnn/vscode-stylelint#86]
With https://github.com/styled-components/stylelint-processor-styled-components stylelint can lint .jsx or .js files that contain styled-components css. However, this plugin doesn't seem to lint jsx or js, even though running stylelint from the cli for the same project does work as expected.

See https://github.com/ismay/ismaywolff.nl for an example of a project using https://github.com/styled-components/stylelint-processor-styled-components, which I used to test this plugin.

**Comment by shinnn** [comment]
Try [`additionalDocumentSelectors`](https://github.com/shinnn/vscode-stylelint/tree/068755c2fe3cec7df2df2cc065a18affe7125c3b#stylelintadditionaldocumentselectors) option.

**Comment by ismay** [comment]
Ah sorry, didn't see that option. That did it. Works perfectly!

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/112#issuecomment-374552740
