### ISSUE TITLE
Plugin icon not showing 

### ISSUE THREAD

**Issue by alexandernanberg** [shinnn/vscode-stylelint#87]
The plugin icon is not showing for me, because the one I'm seeing is a placeholder right?
![image](https://user-images.githubusercontent.com/8997319/28152754-5e97ed1a-67a2-11e7-8116-b7ce594626eb.png)

**Comment by shinnn** [comment]
Thanks for the report, but I'm not very interested in tackling this error because there is no actual impact on this extension.

**Comment by alexandernanberg** [comment]
Okay , but would you accept a pull request that fixes it?

**Comment by coliff** [comment]
Would like to see an icon added too.

**Comment by shinnn** [comment]
I changed my mind and fixed this in https://github.com/shinnn/vscode-stylelint/commit/3c18f04fc511bb429b322ab3833e1ba5fb4358fe.
