### ISSUE TITLE
How to lint style in *.vue files

### ISSUE THREAD

**Issue by Ttou** [shinnn/vscode-stylelint#88]
when add `"vue"` in `additionalDocumentSelectors`, it will report an error in vue file
![test-fs8](https://user-images.githubusercontent.com/4298437/28196555-0cacc024-6884-11e7-931e-49b7ae737e32.png)

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/pull/48#issuecomment-311929024

**Comment by agaripian** [comment]
@shinnn can you give me some more context on how to fix this issue? None of my Vue files are currently being linted by stylelint.

**Comment by shinnn** [comment]
I added a link to my last comment.

**Comment by shinnn** [comment]
Now this extension validates documents with `vue` language identifier by default. https://github.com/shinnn/vscode-stylelint/commit/c554d7afa6e2f3af7bb4dd5b09d14206ced72883
