### ISSUE TITLE
[Suggestion] Add option to disable popup messages

### ISSUE THREAD

**Issue by hugogrochau** [shinnn/vscode-stylelint#89]
When I'm editing `.js` files with the stylelint plugin active, I get spammed with popup error messages from `babylon`. 

For example:
```
SyntaxError: Unexpected token, expected ;(50:12) at Parser.pp$5.raise (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:4454:13) at Parser.pp.unexpected (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:1761:8) at Parser.pp.semicolon (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:1742:38) at Parser.pp$1.parseVarStatement (/home/hugo/projects/liber/liber-app/node_modules/babylon/lib/index.js:2170:8) at Parser.p
```

Here's my .stylelintrc:
```
{
  "processors": ["stylelint-processor-styled-components"],
  "plugins": ["stylelint-order"],
  "extends": "stylelint-config-standard",
  "syntax": "scss"
}
```

I would really like a config option to disable all popup messages from the extension.

Thanks for the extension by the way. It's been helping me a lot so far!

**Comment by shinnn** [comment]
Seems more like a bug of stylelint-processor-styled-components.

Can you show me your `.js` file that causes popup messages?

**Comment by hugogrochau** [comment]
Any file that has any type of syntax error will cause the popup message.

If I have a file with just
```
;
```
and then type a `/` it will throw an error

**Comment by hugogrochau** [comment]
I went ahead and implemented this option here:
https://github.com/hugogrochau/vscode-stylelint/commit/846e66dce639c8fb3859773fc910d042968f433f

Let me know if it's something you'd want to merge

**Comment by shinnn** [comment]
OK, so this is, as I assumed, a bug of stylelint-processor-styled-components. It doesn't adhere to [the original stylelint behavior to syntax errors](https://github.com/stylelint/stylelint/blob/8.0.0/docs/user-guide/node-api.md#syntax-errors):

> stylelint.lint() does not reject the Promise when your CSS contains syntax errors.
