### ISSUE TITLE
Stylelint: Undefined rule '***'

### ISSUE THREAD

**Issue by mthomes** [shinnn/vscode-stylelint#94]
I am getting an error using **vs-code-stylelint** in VS code causing it to no longer lint my styles.

```
stylelint: Undefined rule custom-property-no-outside-root
```

I can remove the rule that it is objecting to, but then I get another undefined rule error. This error is blocking the plugin from linting the rest of the stylesheet.

I also get this drop down error over and over again as I work within the css.
![stylelint-errors](https://user-images.githubusercontent.com/382329/28722588-e1a5f462-7379-11e7-9c29-0570f1013b61.gif)

VSCode Version: 1.14.2
Stylelint Plugin Version: latest

**Comment by shinnn** [comment]
> I can remove the rule that it is objecting to, but then I get another undefined rule error

So, just remove all undefined error.

**Comment by mthomes** [comment]
Having a deprecated rule cause the plugin to completely fail seems like a problem though.

**Comment by shinnn** [comment]
No. Those are not deprecated but entirely removed.

**Comment by shinnn** [comment]
Tracked at https://github.com/stylelint/stylelint/issues/3147.
